ENH: ShadowServer's Radmin feed
certtools/intelmq pull request #1600
Opened 2020-08-17 14:54 UTC by sinus-x

2020-08-21 06:38 UTC, wagner-certat commented
We receive the Radmin feed, but I couldn't find the CAIDA IP Spoofer feed in our inbox (I searched for CAIDA as well as for Spoofer). @th-certbund do you receive this one?

2020-08-21 06:53 UTC, wagner-certat requested changes
Thank you for this contribution!

I currently only have a small comment on the Radmin feed. As I don't have access to a CAIDA IP Spoofer report myself currently, I postpone the review of that one until I get a report somewhere. (If it turns out that it lasts longer, I will merge the Radmin commit before)

2020-08-21 06:53 UTC, wagner-certat commented on intelmq/bots/parsers/shadowserver/config.py
> +    'optional_fields': [
I'm missing the `version` field here. Value is mostly `Radmin v3.X Radmin Authentication`

2020-08-21 06:56 UTC, wagner-certat commented
P.S.: The most recent CAIDA IP Spoofer Report I have is 2020-07-19, so the question is only if these feed is still "active"

2020-08-21 06:59 UTC, wagner-certat commented on intelmq/bots/parsers/shadowserver/config.py
> +        ('extra.', 'version', validate_to_none),
That's the IP version which is obvious from the address and network, maybe we can just drop it.

2020-08-24 10:53 UTC, JakubOnderka commented
> P.S.: The most recent CAIDA IP Spoofer Report I have is 2020-07-19, so the question is only if these feed is still "active"

Our last report is from 2020-08-21, so it is still active.

2020-08-24 11:46 UTC, wagner-certat commented
> > P.S.: The most recent CAIDA IP Spoofer Report I have is 2020-07-19, so the question is only if these feed is still "active"
> 
> Our last report is from 2020-08-21, so it is still active.

Thanks for checking!

2020-08-24 12:13 UTC, wagner-certat commented on intelmq/bots/parsers/shadowserver/config.py
> +        ('extra.', 'version', validate_to_none),
It does, but I had to look at the code myself too :)
Using `False` as field name:
https://github.com/certtools/intelmq/blob/6a657269b0e3ac7518d6e7b8e49535ee154e36b9/intelmq/bots/parsers/shadowserver/parser.py#L184-L187
I will add this to the module-docstring in `config.py`.

2020-08-24 12:13 UTC, wagner-certat commented on intelmq/bots/parsers/shadowserver/config.py
> +    'optional_fields': [
of course, thanks

2020-08-24 12:44 UTC, wagner-certat commented
I'm unsure about the classification, I'll try to clarify that. As that may take some time, this PR is hereby merged and scheduled for the next bugfix release :)

As the filename for the caida feed is not `scan_caida` but `caida_ip_spoofer` I adapted the mappings and file names.

Thanks @sinus-x @JakubOnderka 

Follow-up commits: 96ff28b2e65c1912f0f86c68a60af76e89b0e45f 46ef34048ee037d1313bcbdfea1d059c03ffc480

2020-08-24 12:44 UTC, merged