Add GPG signature verification
certtools/intelmq pull request #1602
Opened 2020-08-19 10:38 UTC by sinus-x

Add support for signature verification to HTTP collector.

Requires [`python-gnupg`](https://pypi.org/project/python-gnupg/). Public keys have to be added manually to the `intelmq` user's keyring.

New parameters:
- `use_gpg`: Whether to download and verify signatures
- `gpg_suffix`: String added after the constructed `http_url`, defaults to `.asc`
- `gpg_keyring`: Path to keyring, defaults to `None`, in which case the default path is used

Tested with Turris Greylist feed. Not tested with feeds that require unzipping or any other manipulation with recieved data.

2020-08-28 09:16 UTC, wagner-certat requested changes
Very cool, Thank you very much for your efforts!

Do you know of any feed where we can use this functionality?

2020-08-28 09:16 UTC, wagner-certat commented on .travis.yml
> +  - if [[ $requirements == true ]]; then for file in intelmq/bots/*/*/REQUIREMENTS.txt; do pip3 install -r $file; done; fi
Travis only installs python3 there, so `pip` is not ambiguous. Once Python 4 is released, that will break again. Therefore I see no advantage in changing it.

2020-08-28 09:16 UTC, wagner-certat commented on docs/Bots.md
> +* `verify_gpg_signatures`: `bool`, defaults to `false`. If `true`, signature file is downloaded and report file is checked. On error (missing signature, mismatch, ...), the error is logged and the re
Please add that the python library python-gnupg is also needed.

2020-08-28 09:16 UTC, wagner-certat commented on intelmq/bots/BOTS
> +                "verify_gpg_signatures": false,
This might be nitpicking, but the format is called PGP, not GPG (which is an implementation). Also applies to `gpg_signature_suffix`

2020-08-28 09:16 UTC, wagner-certat commented on intelmq/bots/collectors/http/collector_http.py
> +            result = self.verify_signature(data=resp._content)
Why do you use `resp._content` and not the public method `resp.content`?

2020-08-28 09:16 UTC, wagner-certat commented on intelmq/bots/collectors/http/collector_http.py
> +        http_url = self.parameters.http_url + suffix
That won't work for URL formatting, better provide the actually used URL also as parameter to this method

2020-09-03 15:14 UTC, sinus-x commented
I've updated the code as requested:
- Signature URL is defined in the same way as the main payload URL
- String `PGP` is used instead of `GPG`

All new builds is failing on misconfigured Shadowserver (`ValueError: Could not get a config for 'scan_caida'`), all local tests for this collector are passing.

2020-09-03 15:44 UTC, merged