New Bot for Fireeye Appliances
certtools/intelmq pull request #1745
Opened 2021-02-16 12:33 UTC by CysihZ

Referring to my mail I created a Parser& Bot which is able to Collect and parse data from fireeye mail and file analysis appliances.
We are collection sha1 and MD5 hashed and if there is network communication we are also collecting urls and domains.

2021-02-17 07:21 UTC, schacht-certat commented
Hi @CysihZ,

please squash your commits and write a meaningful commit message. There are also some failing tests from the spelling checker you might want to look at.

2021-02-17 19:01 UTC, wagner-certat commented
And something appears to be wrong with `docs/user/bots.rst `

On the first *glance*, the tests look good :)

2021-02-17 19:06 UTC, wagner-certat requested changes
In order to make the testsuite work in all cases, small adaptions are necessary. Will do a full review afterwards.

2021-02-17 19:06 UTC, wagner-certat commented on intelmq/bots/parsers/fireeye/parser.py
> +import xmltodict
In order to make the basic test suite work, wrap this in a try-except please. And the same logic for the init-method as for the collector applies here as well.

2021-02-17 19:06 UTC, wagner-certat commented on intelmq/tests/bots/collectors/fireeye/test_collector.py
> +@requests_mock.Mocker()
Please add a `test.skip_exotic()` above this line. The same applies to the parser test. Then, the tests should also be working if the optional library xmltodict is not installed.

2021-04-08 15:08 UTC, wagner-certat commented
Is the code itself ready? If yes, I can fix the remaining issues myself as they are not bot-related by cherry-picking the relevant commits, eventually squashing them together, fixing merge conflicts.

2021-05-03 09:26 UTC, CysihZ commented
Hi, 
sorry for the delay. 
Sounds great, yes  the code itself  is ready!

2021-05-05 14:59 UTC, wagner-certat commented
Incorporated in and obsoleted by #1929
Thanks again!

2021-05-05 14:59 UTC, closed without merging