ENH: get rid of the defaults file
certtools/intelmq pull request #1814
Opened 2021-03-16 11:02 UTC by schacht-certat

The defaults file was used to define global settings. This commit drops
the defaults file as a separate files and instead uses the 'global' key
in the runtime conf to define settings that should be effective in every
bot.
To accomplish that there is now a utils.get_global_settings() function
that extracts the 'global' dict from the runtime configuration file.

2021-03-16 15:17 UTC, wagner-certat requested changes
`defaults.conf` is still mentioned in the docs.

The file itself is also still there, do you plan to remove that in a separate PR? And then we need an upgrade function to
1) migrate the values (only those which differ them the internal defaults) to the runtime config
2) remove the file

2021-03-16 15:56 UTC, wagner-certat commented
In https://github.com/certtools/intelmq/blob/01e8d0184b45d5247723844dd43c7d4d8e7b42da/intelmq/bin/intelmqctl.py#L1522 the "global" (non)bot needs to be skipped

2021-04-01 10:19 UTC, waldbauer-certat approved these changes

2021-04-06 09:26 UTC, schacht-certat commented on intelmq/lib/test.py
> +    return BOT_CONFIG
An empty dict does not work but I've reduced the values as much as possible.

2021-04-06 09:28 UTC, schacht-certat commented
> `defaults.conf` is still mentioned in the docs.

fixed.

> 
> The file itself is also still there, do you plan to remove that in a separate PR?

fixed.

> And then we need an upgrade function to
> 
>     1. migrate the values (only those which differ them the internal defaults) to the runtime config
> 
>     2. remove the file

I added an upgrade function that removes the file and migrates the values, but I'm not sure how to find out how the values differ from internal defaults- the internal defaults might be distributed over multiple files...

2021-04-06 09:32 UTC, schacht-certat commented
> In
> 
> https://github.com/certtools/intelmq/blob/01e8d0184b45d5247723844dd43c7d4d8e7b42da/intelmq/bin/intelmqctl.py#L1522
> the "global" (non)bot needs to be skipped

fixed

2021-04-07 17:07 UTC, wagner-certat requested changes
I'm missing docs in changelog (short) and the NEWS file (explanation to users, what happens on upgrade, e.g. values are migrated to runtime to global, user should check if some values are obsolete etc.)

2021-04-08 07:11 UTC, schacht-certat commented on docs/user/configuration-management.rst
> -*******************************
Fixed

2021-04-08 07:11 UTC, schacht-certat commented on docs/user/configuration-management.rst
> +You can change the broker for single bots (set the parameters in the runtime configuration per bot) or for the whole botnet.
Fixed

2021-04-08 07:30 UTC, wagner-certat requested changes

2021-04-08 07:30 UTC, wagner-certat commented on NEWS.md
> +The `intelmqctl upgrade` command migrates the existing values from the `defaults.conf` file to the `runtime.conf` file under the `global` section and then deletes the `defaults.conf` file.
It's `intelmqctl upgrade-config` :)

2021-04-08 07:36 UTC, wagner-certat approved these changes

2021-04-08 07:37 UTC, merged