[DOC] Renamed DHO to IDF
certtools/intelmq pull request #1818
Opened 2021-03-17 09:46 UTC by waldbauer-certat

Renaming IntelMQ Data Harmonization to IntelMQ Data Format. Internal files will remain and work the same as before.

Closes #1810

2021-03-22 17:49 UTC, wagner-certat requested changes
We should get rid of the trailing whitespaces of course, but I'd prefer a separate commit as there are a lot of them. (should be reasonable easy to separate with git reset and git add -p).

Please add an entry to the changelog and the news file as well.

Looks very good.

2021-03-22 17:49 UTC, wagner-certat commented on docs/dev/data-format.rst
> +In IntelMQ version 3.x+ the internal data format changed from DHO ( IntelMQ Data Harmonization ) to IDF ( IntelMQ Data Format ).
The *name* changed ("... the internal data format name changed ..." or similar)

2021-03-22 17:49 UTC, wagner-certat commented on docs/dev/data-format.rst
> +The python module and the configuration file kept the name `harmonization`. DHO and IDF are working similar.
please name the module/file explicitly.

> The python module ``intelmq.lib.harmonization`` and the configuration file ``harmonization.conf`` keep the name `harmonization` for now. DHO and IDF have the same meaning.

2021-03-25 09:58 UTC, wagner-certat approved these changes

2021-04-06 08:45 UTC, schacht-certat approved these changes

2021-04-07 17:50 UTC, wagner-certat commented
Merged in 5ec55cad1e0d52c191886b8add780e6de7e238c2

2021-04-07 17:50 UTC, closed without merging

2021-04-07 17:53 UTC, wagner-certat commented
Looks like there was a change to the first commit after the merge. Cherry picked that now with e691090403c1d2b80d1b5ddb46f92735ef9aa75c.

Strangely, I can't find the commit with the whitespace fix, but `git cp c2653` says, the pick would be empty, so I guess the change is in develop?