ENH: LookyLoo expert bot for automated website screenshots
certtools/intelmq pull request #1844
Opened 2021-04-07 12:03 UTC by waldbauer-certat

2021-04-07 18:01 UTC, wagner-certat requested changes
That fixes #1048, please add it to the commit message

2021-04-07 18:09 UTC, wagner-certat requested changes
Please add documentation to `docs/user/bots.rst`.

2021-04-08 14:55 UTC, wagner-certat requested changes

2021-04-08 14:55 UTC, wagner-certat commented on intelmq/bots/experts/lookyloo/expert.py
> +            raise MissingDependencyError("pylookyloo, version='>=0.6'")
```suggestion
            raise MissingDependencyError("pylookyloo", version=">=0.6")
```

2021-04-08 14:55 UTC, wagner-certat commented on intelmq/bots/experts/lookyloo/expert.py
> +        event.add('screenshot_url', url)
```suggestion
        if 'source.url' in event:
            url = self.__instance.enqueue(url=event.get('source.url'), user_agent=self.http_user_agent)
            event.add('screenshot_url', url)
```

2021-04-08 14:55 UTC, wagner-certat commented on docs/user/bots.rst
> +LookyLoo
```suggestion
Lookyloo
```

2021-04-08 14:55 UTC, wagner-certat commented on docs/user/bots.rst
> +Sends an request to a LookyLoo instance & saves the website screenshot link into `screenshot_url`.
```suggestion
Lookyloo is a website screenshotting and analysis tool. For more information and installation instructions visit https://www.lookyloo.eu/

The bot sends a request for `source.url` to the configured Lookyloo instance and saves the retrieved website screenshot link in the field `screenshot_url`. Lookyloo only *queues* the website for screenshotting, therefore the screenshot may not be directly ready after the bot requested it.

The `pylookyloo` library is required for this bot.
The `http_user_agent` parameter is passed on, but not other HTTP-related parameter like proxies.

Events without `source.url` are ignored.
```

2021-04-09 11:00 UTC, wagner-certat approved these changes

2021-04-12 06:02 UTC, schacht-certat approved these changes

2021-04-12 08:59 UTC, merged