TST: simplify threshold tests
certtools/intelmq pull request #1946
Opened 2021-05-11 13:57 UTC by wagner-certat

don't sleep, just flush the database
set the common parameters once
use the dedicated test database, works around a bug:
BotTestCase.setUpClass sets up the cache, but it doesn't know of the
redis database which the test will use. So let's just use the same.

fixes a test fail of #1939

2021-05-12 11:08 UTC, waldbauer-certat requested changes

2021-05-12 11:08 UTC, waldbauer-certat commented on intelmq/tests/bots/experts/threshold/test_expert.py
> +        print('keys', self.cache.keys())
Debug?

2021-05-14 08:01 UTC, wagner-certat commented on intelmq/tests/bots/experts/threshold/test_expert.py
> +        print('keys', self.cache.keys())
Thx

2021-05-14 09:08 UTC, waldbauer-certat approved these changes
LGTM

2021-05-14 10:17 UTC, merged