Add new bot: bro  output file
certtools/intelmq pull request #1963
Opened 2021-05-26 08:41 UTC by mariuskarotkis

Add new bot: bro output file

2021-06-07 15:14 UTC, wagner-certat commented
What is bro? Are the fields fixed in bro, or is this user-/implementation-specific?

2021-06-08 05:28 UTC, mariuskarotkis commented
> What is bro? Are the fields fixed in bro, or is this user-/implementation-specific?

Bro intel (zeek) for IDS.

2021-06-08 05:33 UTC, wagner-certat commented
https://zeek.org/2019/09/23/zeek-3-0-0/ indicates that bro has been renamed to zeek. is this output bot only compatible to bro or to zeek as well? Is there any format specification available? Are the fields fixed in bro, or is this user-/implementation-specific?

2021-06-08 06:29 UTC, mariuskarotkis commented
> https://zeek.org/2019/09/23/zeek-3-0-0/ indicates that bro has been renamed to zeek. is this output bot only compatible to bro or to zeek as well? Is there any format specification available? Are the fields fixed in bro, or is this user-/implementation-specific?

This was made bro intel, but the format I think should fit and zeek (needs testing).

2021-08-25 16:01 UTC, wagner-certat commented on intelmq/tests/bots/outputs/bro_file/test_output.py
> +    #     self.assertLoglineEqual(line_no=47, message="source.ipEvent did not have Bro indicator types.",
if you don't know the exact line number or it doesn't make sense, why not use `assertLogMatches`?

2021-09-17 10:03 UTC, wagner-certat requested changes
Just a minor comment on how default values are set, otherwise ready for merge!

2021-09-17 10:03 UTC, wagner-certat commented on intelmq/bots/outputs/bro_file/output.py
> +        self.errors = getattr(self, 'encoding_errors_mode', 'strict')
```suggestion
```
This is set to strict already on line 27, and it's ensured that it's always set. (if you remove it, you'd need to rename the other usages of this variable as well.

2021-09-17 10:03 UTC, wagner-certat commented on intelmq/bots/outputs/bro_file/output.py
> +        self.format_filename = getattr(self, 'format_filename', False)
```suggestion
```
The default value is already `False` on line 30

2021-09-17 18:41 UTC, wagner-certat approved these changes

2021-09-17 18:51 UTC, merged

2021-09-17 18:56 UTC, wagner-certat commented
Thank you also for this nice addition! Apologies for the delays again - we very much value your contributions and your commitment!