Add new bot: cut string by delimeter, max length
certtools/intelmq pull request #1967
Opened 2021-05-26 08:50 UTC by mariuskarotkis

Add new bot: cut string by delimeter, max length

2021-06-14 08:42 UTC, schacht-certat requested changes
Making a string shorter in the Python world is usually called `truncating` (see for example the [jinja2 truncate](https://jinja.palletsprojects.com/en/3.0.x/templates/#jinja-filters.truncate) filter), so calling the bot something like `TruncateByDelimiter` is maybe a more descriptive name.

Please also add a reuse compliant license and copyright header to the files.

As a long term solution it might make more sense to implement a separate bot for string field manipulation, like a JinjaBot which then can do all the jinja filters and which would make it easier to add custom filters. @wagner-certat what do you think?

2021-06-14 08:42 UTC, schacht-certat commented on intelmq/bots/experts/string_cut_delimiter/expert.py
> +    field_for_cut: str = 'source.fqdn'
Please rename this attribute to `field`

2021-06-14 08:42 UTC, schacht-certat commented on intelmq/bots/experts/string_cut_delimiter/expert.py
> +
Please remove the init, if it is not supposed to do anything

2021-06-14 08:42 UTC, schacht-certat commented on intelmq/bots/experts/string_cut_delimiter/expert.py
> +            while (long_string.find(self.string_delimiter) != -1) and (len(long_string) > self.max_length):
`long_string.find(self.string_delimiter) != -1` can be written as `self.string_delimiter in long_string`

2021-06-14 08:42 UTC, schacht-certat commented on intelmq/bots/experts/string_cut_delimiter/expert.py
> +    string_delimiter: str = '.'
I think it would be oke if we just name that attribute `delimiter`

2021-06-14 08:42 UTC, schacht-certat commented on intelmq/bots/experts/string_cut_delimiter/expert.py
> +                long_string = long_string.split(self.string_delimiter, 1)[1]
I think it is more readable if you write:
`long_string, _ = long_string.rsplit(self.string_delimiter, 1)`

2021-08-05 16:48 UTC, wagner-certat requested changes
Could you please add a license header like
```
# SPDX-FileCopyrightText: 2018 <your name/mailaddress>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
```
to
* intelmq/bots/experts/truncate_by_delimiter/expert.py
* intelmq/tests/bots/experts/truncate_by_delimiter/test_expert.py
Thanks

Please describe better, how the bot works so that it's not necessary to study the code before using it. It's not clear from the current docs how delimiter and max_length work together. Maybe add some usage examples which demonstrate it's capabilities, e.g. with max_length = 0 and max_length > 0, and a.b.c.example.com with max_length = 13 and = 15.

2021-08-06 14:23 UTC, wagner-certat approved these changes

2021-08-06 14:27 UTC, merged

2021-08-06 14:44 UTC, wagner-certat commented
Thanks again for your contribution! And sorry for the long waiting time - several issues at the same time forced us to set the focus elsewhere :/