Feeds documentation: Add benkow panels tracker
certtools/intelmq pull request #1998
Opened 2021-06-21 12:07 UTC by certxlm

Hello,

Here is an updated version of the YAML feed configuration file that integrates one of the Benkow feeds.
Source page: http://benkow.cc/passwords.php

Feel free to give me feedback if my commit needs to be changed.

Thanks

2021-06-23 08:17 UTC, wagner-certat requested changes
Thanks for the addition! I have some minor remarks/comments on some details.

2021-06-23 08:17 UTC, wagner-certat commented on intelmq/etc/feeds.yaml
> +              - time.source|__IGNORE__
The malware name can't be invalid, so we don't need to ignore anything. For the IP column we can set the required flag to false. For the time, I don't see a reason to ignore it. (Tested locally and it worked for me)
```suggestion
            columns:
              - __IGNORE__
              - malware.name
              - destination.url
              - destination.fqdn|destination.ip
              - time.source
              columns_required:
              - false
              - true
              - true
              - false
              - true
```

2021-06-25 09:09 UTC, certxlm commented on intelmq/etc/feeds.yaml
> +            type: malware
Where can I find the full taxonomy please?
It's not easy to fit this into the given list as it's about malware/botnet panels.
The closest is probably `c2-server`. What do you think about it?

2021-06-25 09:12 UTC, wagner-certat commented on intelmq/etc/feeds.yaml
> +            type: malware
The upstream taxonomy is as https://github.com/enisaeu/Reference-Security-Incident-Taxonomy-Task-Force/blob/master/working_copy/humanv1.md and https://github.com/enisaeu/Reference-Security-Incident-Taxonomy-Task-Force/blob/master/working_copy/machinev1 for JSON-format. And in the intelmq documentation here: https://intelmq.readthedocs.io/en/latest/dev/data-format.html#classification (please note that this is the latest-version, not maintenance, of the docs)

c2-server looks fine for me. The users still can adapt it if they choose other options.

2021-06-25 11:09 UTC, certxlm commented on intelmq/etc/feeds.yaml
> +            type: malware
Thanks !
Fixed !

2021-06-25 14:05 UTC, wagner-certat approved these changes

2021-06-25 14:19 UTC, wagner-certat approved these changes

2021-06-25 14:19 UTC, wagner-certat commented on intelmq/etc/feeds.yaml
> +              columns_required:
```suggestion
            columns_required:
```

2021-06-25 14:19 UTC, wagner-certat commented on intelmq/etc/feeds.yaml
> +      description: Benkow Panels tracker is a list of fresh panel from various malware. The feed is available on the webpage: http://benkow.cc/passwords.php
```suggestion
      description: "Benkow Panels tracker is a list of fresh panel from various malware. The feed is available on the webpage: http://benkow.cc/passwords.php"
```
YAML doesn't like the colon

2021-06-25 14:21 UTC, wagner-certat commented
Thanks for the addition!

If you know of any other feeds which could be added to the list, your contributions are welcome! Also private feeds, as long as the information about their existence can be shared.

There's a bug in the documentation-generating code, which I'll fix directly. I'm also squashing the commits into one for merging.

2021-06-25 14:25 UTC, wagner-certat commented
Fixed the mentioned (unrelated) bug in 9058c9cc2347e93067430cc44e6ef2feadcbb46d

2021-06-25 14:27 UTC, merged