DOCS: Docker-compose commands updated
certtools/intelmq pull request #2035
Opened 2021-08-11 18:36 UTC by waldbauer-certat

Updated docker-compose install instructions

2021-08-13 08:29 UTC, wagner-certat commented
A note to install docker _and docker-compose_ can also be added (i.e. the programs are required and not installed automatically as dependency or whatsoever)

2021-08-16 16:35 UTC, wagner-certat requested changes

2021-08-16 16:35 UTC, wagner-certat commented on docs/user/FAQ.rst
> +Write the following inside the configuration file, and edit the ``http(s)://<your-domain>`` to your domain name.
```suggestion
Write the following inside the configuration file, and change the ``http(s)://<your-domain>`` to your domain name.
```

2021-08-17 14:06 UTC, wagner-certat approved these changes

2021-08-18 07:37 UTC, schacht-certat commented on docs/user/intelmq-api.rst
> +However, knowledge about Python system administration experience is recommended if you do so.
That `and` was probably at the wrong place and it should be `Python **and** system administration experience`

2021-08-24 16:11 UTC, wagner-certat commented
@waldbauer-certat This can be merged

2021-08-25 09:34 UTC, merged

2021-08-25 11:14 UTC, wagner-certat commented
Cherry-picked for maintenance