DOCS: Added better description for trusted introducer
certtools/intelmq pull request #2044
Opened 2021-08-16 11:32 UTC by waldbauer-certat

Fixes #2017

2021-08-16 15:55 UTC, wagner-certat requested changes
The information, what is stored where in the message is still missing.

2021-08-17 08:51 UTC, schacht-certat requested changes

2021-08-17 08:51 UTC, schacht-certat commented on docs/user/bots.rst
> +After a match, then the abuse contact will be fetched from the trusted introducer teams list and will be stored in the event as `source.abuse_contact`.
*After a match, the abuse contact will ...* (without the `then`)

2021-08-17 08:51 UTC, schacht-certat commented on docs/user/bots.rst
> +If there is a no match, the event will not be enriched and will be sent to the next configured step.
*If there is no match...* (without the `a`)

2021-08-17 14:09 UTC, wagner-certat approved these changes
what @schacht-certat said

2021-08-24 06:16 UTC, schacht-certat commented
![Screenshot_2021-08-24 Bots — intelmq 3 0 1 beta1 documentation](https://user-images.githubusercontent.com/72209253/130564899-515966a7-a92e-4155-b48d-072524c2ef09.png)
This doesn´t render very readable. Not sure what you were going for with the `*` symbol in the beginning of the line, if the goal was to make a listing, you should remove the whitespaces in front of the `*`.
The single tick isn´t a special character in RST, maybe you wanted to use backticks instead, like you did with `source.fqdn`?
I would remove the `*` before the `.com` because it is interpreted as an anchor by RST.
Also you could use → instead of `->` to make it more readable.

2021-08-25 09:20 UTC, schacht-certat approved these changes

2021-08-25 09:35 UTC, merged