Add support for new feeds to Dataplane parser
certtools/intelmq pull request #2102
Opened 2021-09-07 11:34 UTC by monoidic

This PR adds support for all of the currently available Dataplane feeds, i.e dns{rd{,any},version}, proto41, smtp{data,greet} telnetlogin and vncrfb, in addition to the ones currently supported.
Some general code changes to the parser were also made.
Tests for the newly supported feeds were also added, along with a rework of the tests.

2021-09-08 16:55 UTC, wagner-certat requested changes
I would appreciate entries in `intelmq/etc/feeds.yaml` :)

Apart from that I found nothing to complain about ;)

2021-09-09 14:04 UTC, monoidic commented
I added the documentation, plus a helper function called `_convert_datetime` to ensure `extra.first_seen` is converted to IntelMQ DateTime.

2021-09-17 09:48 UTC, wagner-certat approved these changes

2021-09-17 09:50 UTC, merged

2021-09-17 09:55 UTC, wagner-certat commented
Thank you!