FIX: Fixes update-database script on the last few days of a month.
certtools/intelmq pull request #2121
Opened 2021-10-26 11:09 UTC by gethvi

This should fix #2088.

2021-10-29 14:40 UTC, ghost requested changes

2021-10-29 14:40 UTC, ghost commented on intelmq/bots/experts/asn_lookup/expert.py
> +                if days:
```suggestion
                new_url = url + str(months[i]) + "/RIBS/"
                response = session.get(new_url)
                pattern = re.compile(r"href=\"(rib\.\d{8}\.\d{4}\.bz2)\"")
                days = pattern.findall(response.text)
                days.sort(reverse=True)
                if days:
                    url = new_url
```
Otherwise we end up with no result as http://archive.routeviews.org/route-views4/bgpdata/2021.11/RIBS/2021.10/RIBS/ is queried.

2021-11-01 09:44 UTC, gethvi commented on intelmq/bots/experts/asn_lookup/expert.py
> +                if days:
Thanks! Sorry about bad PR. Should be fixed now.

2021-11-26 15:39 UTC, sebix approved these changes
The Pull Request looks semantically OK. The PR can be merged as soon as someone reviews and validates the exact code changes and documents the change in the changelog.

2021-12-01 12:55 UTC, waldbauer-certat approved these changes

2021-12-01 13:03 UTC, merged