ENH: Added personal access token support to GitHub Collector
certtools/intelmq pull request #2145
Opened 2022-02-01 11:52 UTC by waldbauer-certat

As github basic authentication has been marked as deprecated by
GitHub, we now implemented the Personal Access Token authentication
method.

Fixes #1549

2022-02-01 21:02 UTC, sebix requested changes
Please add a note to the NEWS file on the parameter change

https://developer.github.com/changes/2020-02-14-deprecating-password-auth/#removal says:

> All password authentication will return a status code of 401 starting:
> 
>     November 13, 2020 at 16:00 UTC

So I guess the old auth does no longer work? If that's the case, please remove the old method, it's of no use.

the `feeds.yml` needs an update as well: https://intelmq.readthedocs.io/en/latest/user/feeds.html#id123

2022-02-01 21:02 UTC, sebix commented on CHANGELOG.md
> +- `intelmq.bots.collectors.github_api._collector_github_api`: Added personal access token support (PR#2145 by Sebastian Waldbauer).
```suggestion
- `intelmq.bots.collectors.github_api._collector_github_api`: Added personal access token support (PR#2145 by Sebastian Waldbauer, fixes #1549).
```

2022-02-01 21:02 UTC, sebix commented on docs/user/bots.rst
> +* `personal_access_token:` GitHub account personal access token (optional)
```suggestion
* `personal_access_token:` GitHub account personal access token ([GitHub documentation: Creating a personal access token](https://developer.github.com/changes/2020-02-14-deprecating-password-auth/#removal))
```

2022-02-02 08:31 UTC, waldbauer-certat commented
> Please add a note to the NEWS file on the parameter change
> 
> https://developer.github.com/changes/2020-02-14-deprecating-password-auth/#removal says:
> 
> > All password authentication will return a status code of 401 starting:
> > ```
> > November 13, 2020 at 16:00 UTC
> > ```
> 
> So I guess the old auth does no longer work? If that's the case, please remove the old method, it's of no use.
> 
> the `feeds.yml` needs an update as well: https://intelmq.readthedocs.io/en/latest/user/feeds.html#id123

Feeds will be auto build, no? Because its gitignored https://github.com/certtools/intelmq/blob/develop/.gitignore#L30

2022-02-02 08:32 UTC, sebix commented
> > So I guess the old auth does no longer work? If that's the case, please remove the old method, it's of no use.
> > the `feeds.yml` needs an update as well: https://intelmq.readthedocs.io/en/latest/user/feeds.html#id123
> 
> Feeds will be auto build, no? Because its gitignored https://github.com/certtools/intelmq/blob/develop/.gitignore#L30

That page is generated from `intelmq/etc/feeds.yml`

2022-02-11 08:20 UTC, sebix commented on intelmq/tests/bots/collectors/github_api/test_collector.py
> -
Is there no replacement possible?

2022-02-11 08:20 UTC, sebix commented on intelmq/etc/feeds.yaml
> +
are you sure that these whitespace removals do not affect the rendering?

2022-07-06 09:43 UTC, sebix requested changes

2022-07-06 09:43 UTC, sebix commented on CHANGELOG.md
> +- `intelmq.bots.collectors.mail._lib`: Add support for unverified SSL/STARTTLS connections (PR#2055 by Sebastian Wagner).
I don't see this change in this PR

2022-07-06 09:43 UTC, sebix commented on intelmq/bots/collectors/github_api/_collector_github_api.py
> +from intelmq.lib.exceptions import MissingDependencyError
```suggestion
```

2022-07-06 09:43 UTC, sebix commented on intelmq/bots/collectors/github_api/_collector_github_api.py
requests is a dependency of IntelMQ Core itself already

2022-07-06 09:43 UTC, sebix commented on intelmq/bots/collectors/github_api/_collector_github_api.py
> +        if self.personal_access_token is not None:
Treating empty string equally to None
```suggestion
        if self.personal_access_token:
```

2022-07-06 09:43 UTC, sebix commented on intelmq/bots/collectors/github_api/_collector_github_api.py
> +    personal_access_token: str = None
None is not a string
```suggestion
    personal_access_token: Optional[str] = None
```

2022-07-06 09:46 UTC, sebix commented
And:
```
==================================== ERRORS ====================================
______ ERROR at setup of test_collector_should_fail_with_bad_credentials _______
file /home/runner/work/intelmq/intelmq/intelmq/tests/bots/collectors/github_api/test_collector.py, line 96
  @patch('intelmq.bots.collectors.github_api.collector_github_contents_api.requests.get')
  def test_collector_should_fail_with_bad_credentials(self, requests_get_mock):
E       fixture 'requests_get_mock' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, doctest_namespace, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, requests_mock, time_machine, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
/home/runner/work/intelmq/intelmq/intelmq/tests/bots/collectors/github_api/test_collector.py:96
---------- coverage: platform linux, python 3.7.13-final-0 -----------
Coverage XML written to file coverage.xml
=========================== short test summary info ============================
ERROR intelmq/tests/bots/collectors/github_api/test_collector.py::test_collector_should_fail_with_bad_credentials
```

2022-07-07 13:58 UTC, sebix requested changes

2022-07-07 13:58 UTC, sebix commented on intelmq/tests/bots/collectors/github_api/test_collector.py
> +
```suggestion

```

2022-07-15 08:44 UTC, sebix commented on intelmq/tests/bots/collectors/github_api/test_collector.py
> -
As [you are keen on codestyle and "Quality of Life"](https://github.com/certtools/intelmq/pull/2211): Before a class statement there should be two empty lines ;)

2022-07-25 13:41 UTC, sebix approved these changes

2022-07-25 13:42 UTC, merged