Fix #2164: Implement skip_header enhancement
certtools/intelmq pull request #2171
Opened 2022-05-03 13:49 UTC by gutsohnCERT

# Please read the notes below and replace them with the description of you pull request

Make sure you follow the instructions in the [Developer Guide](https://intelmq.readthedocs.io/en/latest/dev/guide.html) - it describes how to run the test suite and which coding rules to follow.

# Commits

Please review your commits before creating a pull request. We try to keep our commit history clean.
If you had to fix something in your code and added another commit on top of your existing work, please [squash](https://blog.simontimms.com/2016/02/18/i-squash-my-pull-requests-and-you-should-too/) your commits.
This makes it a lot easier to find out why things work the way they do later on.

But please also keep in mind that one commit should only contain changes that belong together.
> The cardinal rule for creating good commits is to ensure there is only one "logical change" per commit
> - [OpenStack Wiki on GitCommitMessages](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

Thus, if your changes affect multiple files and also contains tests and documentation (which it should), it might make sense to have the tests and the documentation in a separate commit.

# Commit Messages

Please explain your changes also in the git commit message.
The commit message should contain a subject that gives an overview of the changes in the commit and is limited to 72 characters.
It should start with a capital letter and it should not end with a period.
Below the subject should be, separated by an empty line, the body of the commit message. The body should explain what the commit changes and why it changes thing the way it does.
Explain your modification and also explain why you didn't chose a different approach.
See also [How To Write a Git Commit Message](https://chris.beams.io/posts/git-commit/).

# Description

If you are following the commit message guidelines above, all the relevant information should already be part of the commit message.
If there is anything else you want to add, feel free to do this here.

2022-05-05 12:44 UTC, gethvi commented
Thank you for implementing this feature request! I was hoping to get to it myself eventually, but you were faster. :-)

2022-07-25 13:03 UTC, sebix requested changes

2022-07-25 13:03 UTC, sebix commented on intelmq/bots/parsers/generic/parser_csv.py
> +            if isinstance(self.skip_header, int):
Instead of checking the type of the parameter, converting it to int is much easier.

2022-07-25 13:03 UTC, sebix commented on intelmq/tests/bots/parsers/generic/data_type_multiple_header.csv.license
> +SPDX-FileCopyrightText: 2022 gutsohnCERT
```suggestion
SPDX-FileCopyrightText: 2022 CERT.at GmbH
```

2022-07-25 13:03 UTC, sebix commented on intelmq/tests/bots/parsers/generic/test_parser_csv_data_type_multiple_header.py
> +# SPDX-FileCopyrightText: 2017 navtej
```suggestion
# SPDX-FileCopyrightText: 2022 CERT.at GmbH
```

2022-07-25 13:03 UTC, sebix commented
The docs need to be update too.

2023-02-08 15:14 UTC, gethvi commented
This enhancement has been merged as PR #2313.

2023-05-17 10:17 UTC, gethvi commented
Close?

2023-05-17 20:03 UTC, sebix commented
Thanks for the reminder
AFAIK @gutsohnCERT is not active anymore (please object if I'm wrong)
and the feature is already implemented by @gethvi

2023-05-17 20:03 UTC, closed without merging