Add new bot: uri expert
certtools/intelmq pull request #2191
Opened 2022-06-07 12:17 UTC by gutsohnCERT

Add enhancement uri expert bot. The bot parses the input message and it validates the source/destination uris according RFC3986.

Fixes #1768

2022-07-12 12:00 UTC, waldbauer-certat requested changes

2022-07-12 12:00 UTC, waldbauer-certat commented on intelmq/tests/bots/experts/uri/test_expert.py
> +class TestURIExpertBot(test.BotTestCase, unittest.TestCase):
```suggestion
@test.skip_exotic()
class TestURIExpertBot(test.BotTestCase, unittest.TestCase):
```

Test.skip_exotic() is defined in intelmq/lib/test.py

2022-07-12 12:00 UTC, waldbauer-certat commented on intelmq/tests/bots/experts/uri/test_expert.py
> +    from intelmq.bots.experts.uri.expert import URIExpertBot
```suggestion
from intelmq.bots.experts.uri.expert import URIExpertBot
```

You can remove the os.getenv, because its handled by the other suggestion below, using @test.skip_exotic()

2022-07-12 12:00 UTC, waldbauer-certat commented on intelmq/bots/experts/uri/expert.py
> +        uri_validator = validators.Validator().require_presence_of('scheme')
```suggestion
    _uri_validator = None
    
    def init(self):
        if rfc3986 is None:
            raise MissingDependencyError("rfc3986", version=">=1.5")
        self._uri_validator = validators.Validator().require_presence_of('scheme')
    
    def process(self):
        event = self.receive_message()
```

No need to re-initialize the validator everytime an event gets pulled

2022-07-12 12:00 UTC, waldbauer-certat commented on intelmq/bots/experts/uri/expert.py
> +
```suggestion
from intelmq.lib.bot import ExpertBot

try:
    from rfc3986 import uri_reference, validators, exceptions
except ImportError:
    rfc3986 = None
```

2022-07-12 12:00 UTC, waldbauer-certat commented on intelmq/bots/experts/uri/expert.py
> +# SPDX-FileCopyrightText: 2022 gutsohnCERT
```suggestion
# SPDX-FileCopyrightText: 2022 CERT.at GmbH
```

2022-07-12 12:00 UTC, waldbauer-certat commented on intelmq/bots/experts/uri/REQUIREMENTS.txt
> +# SPDX-FileCopyrightText: 2022 gutsohnCERT
```suggestion
# SPDX-FileCopyrightText: 2022 CERT.at GmbH
```

2022-07-12 12:00 UTC, waldbauer-certat commented on intelmq/bots/experts/uri/expert.py
> +            key_query = "{}{}".format(key, "query")
```suggestion
            key_url = f"{key}url"
            key_ip = f"{key}ip"
            key_fqdn = f"{key}fqdn"
            key_scheme = f"{key}scheme"
            key_path = f"{key}path"
            key_userinfo = f"{key}userinfo"
            key_port = f"{key}port"
            key_query = f"{key}query"
```

f-strings have been introduced in python3.6 and improve code readability.

2022-07-12 12:00 UTC, waldbauer-certat commented on intelmq/tests/bots/experts/uri/test_expert.py
> +import os
```suggestion
```

2022-07-12 12:00 UTC, waldbauer-certat commented on intelmq/bots/experts/uri/expert.py
> +                uri_validator.validate(uri_reference(event.get(key_url)))
```suggestion
                self._uri_validator.validate(uri_reference(event.get(key_url)))
```

2022-07-12 19:30 UTC, sebix commented
> @[waldbauer-certat](https://github.com/waldbauer-certat) waldbauer-certat requested a review from [sebix](https://github.com/sebix) 12 hours ago

This PR is marked as draft - is it ready for review/merge?

2022-07-15 07:37 UTC, gutsohnCERT commented
Hi @sebix , could you help me with this psql/harmonization issue? Thx!

2022-07-15 08:28 UTC, sebix commented
> Hi @sebix , could you help me with this psql/harmonization issue? Thx!

You're adding various new fields, which has major impact on the users as they need to adapt the outputs. E.g. for databases, they need to add new columns.

Please open a discussion on intelmq-dev (or: IEP) to propose these new fields and discuss this there.
If the community is in favour of it, we can discuss the technical details how to properly implement and document all that.

2023-05-17 10:16 UTC, gethvi commented
Superseded by #2315. Close?

2023-05-17 20:04 UTC, sebix commented
Same as in #2171 applies, yes

2023-05-17 20:04 UTC, closed without merging