Various documentation updates: Page on Support and Structure
certtools/intelmq pull request #2220
Opened 2022-07-19 18:25 UTC by wagner-intevation

Aside some smaller changes, this adds two new pages to the documentation:
* how to get help (also centralizing the several places where this information was previously and adding it to a prominent page on the index, so users find it quickly)
* a starting point to describe how the IntelMQ community develops and works together, including a short description of the Board, IEPs and a short history of IntelMQ

All of that is by no means complete and should be considered without any claim to comprehensiveness.

2023-01-09 16:22 UTC, kamil-certat requested changes

2023-01-09 16:22 UTC, kamil-certat commented on docs/user/support.rst
> +GitHub also offers a `discussion platform <https://github.com/certtools/intelmq/discussions/landing>`_.
Please remove the `/landing` from link, it doesn't work anymore.

2023-01-09 16:22 UTC, kamil-certat commented on docs/user/universe.rst
> +.. image:: https://raw.githubusercontent.com/certat/intelmq-webinput-csv/master/docs/images/screenshot.png
I'd prefer to include this image in the repo here. Especially, that the link is to the master branch in another repository. It could be changed at any time and break docs. Please either include, or link the specific (e.g. commit-linked) version of the image.

2023-01-09 16:22 UTC, kamil-certat commented on docs/user/universe.rst
> +The certbund-contact consists of two IntelMQ expert bots, whcih fetch and process the information from the contact database, and scripts to import RIPE data into the contact database.
```suggestion
The certbund-contact consists of two IntelMQ expert bots, which fetch and process the information from the contact database, and scripts to import RIPE data into the contact database.
```

2023-01-09 16:22 UTC, kamil-certat commented on docs/user/universe.rst
> +Based on user-defined rules, the experts determine to which contact the event is to be sent to and which e-mail template and attachment format to use.
```suggestion
Based on user-defined rules, the experts determine to which contact the event is to be sent to, and which e-mail template and attachment format to use.
```

2023-01-09 16:22 UTC, kamil-certat commented on docs/user/universe.rst
> +   :alt: IntelMQ Webinput CSV Preview page
Wrong description

2023-01-09 16:22 UTC, kamil-certat commented on docs/user/universe.rst
> +.. image:: https://raw.githubusercontent.com/Intevation/intelmq-fody/master/docs/images/landing_page.png
As with the web-input, please link to a specific version of the image or include it here.

2023-01-09 16:22 UTC, kamil-certat commented on docs/user/universe.rst
> +.. image:: https://gitlab.com/sebix1/tuency/-/raw/master/docs/images/netobjects.png
I'd suggest linking the main Tuency repo (not a fork), and with a commit-assured version.

2023-01-09 16:22 UTC, kamil-certat commented on docs/user/universe.rst
> +.. image:: https://raw.githubusercontent.com/certtools/stats-portal/master/architecture-overview-stats-portal-screen.png
Please link the commit-assured link.

2023-01-20 20:18 UTC, sebix commented on docs/user/universe.rst
> +.. image:: https://gitlab.com/sebix1/tuency/-/raw/master/docs/images/netobjects.png
That image did not exist in the main repo at the time when I created the PR initially

2023-02-02 12:35 UTC, aaronkaplan commented on docs/user/support.rst
> +* `Aaron Kaplan <https://github.com/aaronkaplan/>`_ (founder of IntelMQ)
here we will need to add ossbase

2023-02-02 12:39 UTC, aaronkaplan approved these changes
looks good. Will have to add ossbase later

2023-02-02 19:31 UTC, merged