DOC: Update API docs to work with rewritten API
certtools/intelmq pull request #2292
Opened 2023-01-04 14:00 UTC by kamil-certat

Rewritten API requires configuring web server and services
for manually installation. In addition, some previously
missing information are clarified.

This docs are ready to review, but valid after merging the rewritten API in intelmq-api repository.

2023-01-04 16:29 UTC, gethvi commented
Where can I see the code? :-) I was actually working on my own version of IntelMQ API using FastAPI...

2023-01-05 08:17 UTC, kamil-certat commented
I opened PRs in the API repository in December: https://github.com/certtools/intelmq-api/pull/38 (+depending PR 39 with packaging)

2023-02-02 08:16 UTC, aaronkaplan commented on docs/user/intelmq-api.rst
> +`intelmq-api` is a `FastAPI <https://fastapi.tiangolo.com/>`_ based API for the `IntelMQ <https://github.com/certtools/intelmq/>`_ project.
love it!

2023-02-02 12:25 UTC, aaronkaplan commented
> Where can I see the code? :-) I was actually working on my own version of IntelMQ API using FastAPI...

@gethvi you can see the code in https://github.com/certtools/intelmq-api/

2023-02-02 12:29 UTC, aaronkaplan requested changes
minor typo squatting suggestions.
May I suggest to run this through a spell checker again (use chatGPT or so and instruct it to rewrite it ;-) )

2023-02-02 12:29 UTC, aaronkaplan commented on docs/user/intelmq-api.rst
> +from its `repository <https://github.com/certtools/intelmq-api>`_:
"from this repository" --> typo

2023-02-02 12:29 UTC, aaronkaplan commented on docs/user/intelmq-api.rst
> +Can I use other web server or proxy?
serverS (typo)

2023-02-06 13:53 UTC, kamil-certat commented
@aaronkaplan Done. The ChatGPT was unfortunately busy, but the LanguageTool found a few small issues

2023-02-06 22:17 UTC, aaronkaplan commented
> @aaronkaplan Done. The ChatGPT was unfortunately busy, but the LanguageTool found a few small issues

Thank you very much! Looks great.

2023-07-06 08:09 UTC, sebix commented
I rebased the branch on current develop.

@aaronkaplan This PR is marked by yourself as "changes requested". Please look to see if this PR is OK for you now. I think @kamil-certat addressed the issues you pointed out.

2023-07-06 08:09 UTC, sebix approved these changes

2023-07-17 07:27 UTC, merged