ENH: Drop Python 3.6 and enable 3.11
certtools/intelmq pull request #2294
Opened 2023-01-05 10:23 UTC by kamil-certat

The whole support for Python 3.6, including docs and dependencies, was droped. Some small code changes were made to use newer syntax.

In addition, testing for Python 3.11 was enabled, and changelog was fixed.

Closes #2272

2023-01-05 10:40 UTC, kamil-certat commented
For some reason, the ansible test just failed to start. May I ask for restart?

2023-01-24 16:31 UTC, wagner-intevation requested changes

2023-01-24 16:31 UTC, wagner-intevation commented on CHANGELOG.md
> -    - Respected global and per-bot custom settings of `logging_path` (fix #1605).
Why is the changelog for 2.3.0 changed?

2023-01-24 16:32 UTC, sebix commented
> May I ask for restart?

I trigged it and now it succeeds as expected

2023-01-25 07:53 UTC, kamil-certat commented on CHANGELOG.md
> -    - Respected global and per-bot custom settings of `logging_path` (fix #1605).
Let's see the git blame and the commit message. I've found out that this entry was misplaced by me - the change was made recently, but I've scrolled too down in the changelog and put it wrongly.

2023-01-26 17:24 UTC, merged