FIX: intelmqsetup - never take ownership of /
certtools/intelmq pull request #2355
Opened 2023-04-25 12:14 UTC by kamil-certat

The tool intelmqsetup wants to change the owner ROOT_DIR path.
If instructed to install IntelMQ in LSB-style paths, it's set
to the '/' resulting in changing the owner of system root to
intelmq.

This case is rare to happen (requires explixitly set INTELMQ_PATHS_NO_OPT
variable and using PIP package or directly the source code,
as the native package doesn't contain intelmqsetup), but it's
still potentially dangerous and can cause the system degradation
(e.g. prevents systemd-tmpfiles from working correctly).

Fixes: #2354

2023-05-03 11:09 UTC, sebix requested changes
Except for the changelog change suggestion, ready for merge.
Thanks for the tests :)

2023-05-03 11:09 UTC, sebix commented on CHANGELOG.md
> +  - SECURITY: fixed a low-risk bug causing the tool to change owner of `/` path if running with the `INTELMQ_PATHS_NO_OPT` environment variable set to `True`. This affects only the PIP package as the
The value of `INTELMQ_PATHS_NO_OPT` does not matter as long as it is set (the code checks for existence).
```suggestion
  - SECURITY: fixed a low-risk bug causing the tool to change owner of `/` if run with the `INTELMQ_PATHS_NO_OPT` environment variable set. This affects only the PIP package as the DEB/RPM packages don't contain this tool. (PR#2355 by Kamil Mańkowski, fixes #2354)
```

2023-05-03 11:09 UTC, sebix commented on intelmq/bin/intelmqsetup.py
> +    if Path(file).as_posix() in ['/', '//']:
```suggestion
    if Path(file).as_posix() in ('/', '//'):
```

2023-05-03 11:09 UTC, sebix commented on intelmq/bin/intelmqsetup.py
> +    if Path(file).as_posix() in ['/', '//']:
Why checking for `//`?

2023-05-03 12:34 UTC, kamil-certat commented on intelmq/bin/intelmqsetup.py
> +    if Path(file).as_posix() in ['/', '//']:
It's just an additional precaution, but if you look into [docs](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.root): posix root paths are standardized to `/`, except for `//`. Both are recognized as root directory. In fact, the later case is highly unlikely. It can be only manually set by the user, but even then - IntelMQ should never take the ownership of root.

2023-05-08 12:59 UTC, kamil-certat commented
@sebix Do you have any questions more, or we could merge it?

2023-05-08 16:50 UTC, sebix approved these changes

2023-05-08 16:50 UTC, merged