FIX: Restrict python-rt version
certtools/intelmq pull request #2371
Opened 2023-05-25 14:36 UTC by kamil-certat

The `python-rt` in version 3 introduced some small backward incompatible changes. 

Related changes are tracked in #2367

2023-05-26 06:48 UTC, sebix requested changes
Could you please add a small note in docs/user/bots.rst too?

If the user has rt 3.0.0 installed, the bot will just fail. by checking the rt version in the bot, the error message would be more precise (the mongodb output bot does this for example)

2023-06-01 13:00 UTC, sebix requested changes

2023-06-01 13:00 UTC, sebix commented on docs/user/bots.rst
> +You need the rt-library >= 1.9 and < 3.0 from nic.cz, available via `pypi <https://pypi.org/project/rt/>`_: `pip3 install rt`
```suggestion
You need the rt-library >= 1.9 and < 3.0 from nic.cz, available via `pypi <https://pypi.org/project/rt/>`_: `pip3 install 'rt<3'`
```

2023-06-01 13:00 UTC, sebix commented on docs/user/bots.rst
> +   Actually the bot supports the python-rt library in the version older than 3.0.
```suggestion
   At the moment, the bot only supports `python-rt` versions below 3.0.
```
"Actually" does not mean "now"

2023-06-01 13:15 UTC, kamil-certat commented on docs/user/bots.rst
> +   Actually the bot supports the python-rt library in the version older than 3.0.
Agh, right!

2023-06-07 18:59 UTC, merged