FIX: Ensure rejecting URLs starting with space
certtools/intelmq pull request #2378
Opened 2023-06-14 12:07 UTC by kamil-certat

The gh-102153 change in CPython modified how
urllib.pare handles URLs with the leading
spaces. To ensure previous behaviour, additional
check was added.

Closes: #2377

2023-06-21 11:23 UTC, sebix approved these changes

2023-06-26 08:02 UTC, kamil-certat commented
@sebix Could you take a look, if after my last changes you still approve the PR?

2023-06-27 06:34 UTC, sebix requested changes

2023-06-27 06:34 UTC, sebix commented on CHANGELOG.md
> +
```suggestion
```

2023-06-27 06:50 UTC, merged