Extend intelmq_psql_initdb
certtools/intelmq pull request #2404
Opened 2023-08-31 12:19 UTC by kamil-certat

Added creating view for separating raws, optional partitioning key, 
custom harmonization file path and `if not exists`/`or replace` clauses.

Those changes improves the capabilities of the database
schema creation. It's now easier to switch to the TimescaleDB
or use partitioning in PostgreSQL. Creating scripts can be
generated from the harmonisation, as previously just the most
basic version. If requested, creation commands get IF NOT EXISTS
or OR REPLACE directives to allow re-runing script.

2023-09-05 12:55 UTC, sebix requested changes
Great to see that my design is still useful :)

Is the file `contrib/eventdb/separate-raws-table.sql` obsoleted?

https://intelmq.readthedocs.io/en/develop/user/eventdb.html#separating-raw-values-in-postgresql-using-view-and-trigger needs an update for the new method.

2023-09-05 12:55 UTC, sebix commented on CHANGELOG.md
> + - `intelmq_psql_initdb` got support for providing custom harmonization file, generating view for storing `raw` fields separately, and adding `IF NOT EXISTS`/`OR REPLACE` clauses (PR by Kamil Mankows
```suggestion
 - `intelmq_psql_initdb` got support for providing custom harmonization file, generating view for storing `raw` fields separately, and adding `IF NOT EXISTS`/`OR REPLACE` clauses ([PR#2404](https://github.com/certtools/intelmq/pull/2404) by Kamil Mankowski).
```

2023-09-05 12:55 UTC, sebix commented on intelmq/bin/intelmq_psql_initdb.py
> +                              "If combined with --separate-raws, the v_events does not get foreign key"))
From a user perspective this information is unfortunately not enough to comprehend what this option is used for and how to use it best. Is `time.source` a good option, so also use https://intelmq.readthedocs.io/en/develop/user/eventdb.html#using-eventdb-with-timescale-db ?

2023-09-05 14:12 UTC, kamil-certat commented
Thanks for catching lack of docs, let's see now

2023-09-05 18:37 UTC, sebix approved these changes
Only wording suggestions. LGTM

2023-09-05 18:37 UTC, sebix commented on docs/user/eventdb.rst
> +The EventDB is a database (usually `PostgreSQL <postgresql.org/>`_) that gets filled with with data
```suggestion
The EventDB is a database (usually `PostgreSQL <postgresql.org/>`_) that gets filled with data
```

2023-09-05 18:37 UTC, sebix commented on docs/user/eventdb.rst
> +For full list of supported parameters, call the script help using ``-h`` parameter.
```suggestion
For a full list of supported parameters, call the script help using ``-h`` parameter.
```

2023-09-05 18:37 UTC, sebix commented on docs/user/eventdb.rst
> +Be aware that if you create tables using another DB user that used later by the output bot, you may
```suggestion
Be aware that if you create tables using another DB user that is used later by the output bot, you may
```

2023-09-05 18:37 UTC, sebix commented on docs/user/eventdb.rst
> +All elements of generated SQL file can be adapted and extended before running the SQL file against
```suggestion
All elements of the generated SQL file can be adapted and extended before running the SQL file against
```

2023-09-05 18:37 UTC, sebix commented on docs/user/eventdb.rst
> +You can use :ref:`intelmq_psql_initdb` tool to generate SQL schema valid for TimescaleDB by passing
```suggestion
You can use the :ref:`intelmq_psql_initdb` tool to generate SQL schema valid for TimescaleDB by passing
```

2023-09-05 18:37 UTC, sebix commented on docs/user/eventdb.rst
> +Thanks to TimescaleDB it's very easy to setup.
```suggestion
Thanks to TimescaleDB, it's very easy to setup.
```

2023-09-05 18:37 UTC, sebix commented on docs/user/eventdb.rst
> +``time.source`` or ``time.observation``. Depending on your needs (tracking when event occurred or when
```suggestion
``time.source`` or ``time.observation``. Depending on your needs (tracking when the event occurred or when
```

2023-09-05 18:37 UTC, sebix commented on docs/user/eventdb.rst
> +was detected, if different) choose one of them.
```suggestion
it was detected, if different), choose one of them.
```

2023-09-05 18:37 UTC, sebix commented on docs/user/eventdb.rst
> +To utilize the time-series, you need to choose a column containing the right time. This is then
```suggestion
To utilize the time-series, choose a column containing the right time. This is then
```

2023-09-05 18:37 UTC, sebix commented on docs/user/eventdb.rst
> +used by you for manual queries and graphs, but also by the database itself for organizing the data.
```suggestion
used by you for manual queries and graphs, and also by the database itself for organizing the data.
```

2023-09-26 11:17 UTC, kamil-certat commented
@sebix Would you find time to merge this PR?

2023-09-26 20:30 UTC, merged