Discover bots based on the entry points
certtools/intelmq pull request #2413
Opened 2023-09-21 12:36 UTC by kamil-certat

The bot discovery algorithm was rewritten to use entry point
names instead of the file structure. This allow really easy
developing of packages with custom bots.

Note that the 'group' feature of entry points wasn't used
because we require bots to register callable scripts that
are later used to start bot's processes.

2023-09-26 20:49 UTC, sebix requested changes

2023-09-26 20:49 UTC, sebix commented on CHANGELOG.md
> +- Change the way we discover bots to allow easy extending based on the entry point name. (PR by Kamil Mankowski)
```suggestion
- Change the way we discover bots to allow easy extending based on the entry point name. (PR#2413 by Kamil Mankowski)
```

2023-09-26 20:49 UTC, sebix commented on CHANGELOG.md
> +- Add a guide of developing extensions packages (PR by Kamil Mankowski)
```suggestion
- Add a guide of developing extensions packages (PR#2413 by Kamil Mankowski)
```

2023-09-26 20:49 UTC, sebix commented on contrib/example-extension-package/mybots/bots/collectors/custom/collector.py
> +from intelmq.lib.bot import CollectorBot
The example could additionally show, that import from a own library can be done like this:
```suggestion
from intelmq.lib.bot import CollectorBot
from mybots.lib import common_code
```
or alike

2023-09-26 20:49 UTC, sebix commented on contrib/example-extension-package/mybots/bots/collectors/custom/collector.py
> +    This is an example bot provided by extension package
```suggestion
    This is an example bot provided by an extension package
```

2023-09-26 20:49 UTC, sebix commented on contrib/example-extension-package/setup.py
> +# intelmq.bots.collectors.custom.collector = mybots.bots.collectors.custom.collector:BOT.run
it's a string
```suggestion
# 'intelmq.bots.collectors.custom.collector = mybots.bots.collectors.custom.collector:BOT.run'
```

2023-09-26 20:49 UTC, sebix commented on docs/dev/guide.rst
> +into the main IntelMQ repository.
```suggestion
IntelMQ supports adding additional bots using your own independent packages. You can use this to
add a new integration that is special to you, or cannot be integrated
into the main IntelMQ repository for some reason.
```

2023-09-26 20:49 UTC, sebix commented on docs/dev/guide.rst
> +bots to work with IntelMQ, you need to ensure that
```suggestion
A simple example of the package can be found in ``contrib/example-extension-package``. To make your custom
bots work with IntelMQ, you need to ensure that
```

2023-09-26 20:49 UTC, sebix commented on docs/dev/guide.rst
> +   virtualv).
```suggestion
   virtualenv, if you use them).
```

2023-09-26 20:49 UTC, sebix commented on docs/dev/guide.rst
> +experience when using official and additional bots.
What kind of experience does it ensure?

2023-09-26 20:49 UTC, sebix commented on docs/dev/guide.rst
> +Once you installed your package, you can run ``intelmqctl list bots`` to check if your bot was
```suggestion
Once you have installed your package, you can run ``intelmqctl list bots`` to check if your bot was
```

2023-09-26 20:49 UTC, sebix commented on intelmq/lib/utils.py
> +    bot_entrypoints = filter(lambda entry: entry.name.startswith("intelmq.bots."), _get_console_entry_points())
Is this covered by unit tests?

2023-09-26 20:49 UTC, sebix commented on setup.py
> +    'importlib-metadata; python_version < "3.8"'
Debian 10 buster has Python 3.7 and `python3-importlib-metadata` is only in buster-backports. So please update the installation instructions, adding that activating backports on Debian 10 is necessary and add the package as dependency to `debian/control`. I think it's totally fine to require backports on an old OS version.

2023-09-27 13:36 UTC, kamil-certat commented on docs/dev/guide.rst
> +experience when using official and additional bots.
Looks like I lost some words when copying from language correction tool...

2023-09-27 14:28 UTC, kamil-certat commented on intelmq/lib/utils.py
> +    bot_entrypoints = filter(lambda entry: entry.name.startswith("intelmq.bots."), _get_console_entry_points())
It was indirect tested (we test loading bots, and we have additional entry points in the package). But I've added a direct test for this case. Unfortunately, it's not easy to do it clear without mocking.

2023-09-27 15:47 UTC, sebix requested changes

2023-09-27 15:47 UTC, sebix commented on docs/user/installation.rst
> +  * Enable the backport repository by the line ``deb-src http://deb.debian.org/debian buster-backports main contrib non-free`` to the file ``/etc/apt/sources.list`` first.
```suggestion
  * Enable the backport repository by the line ``deb http://deb.debian.org/debian buster-backports main contrib non-free`` to the file ``/etc/apt/sources.list`` first.
```

2023-09-27 15:48 UTC, sebix commented on docs/user/installation.rst
> +  * Enable the backport repository by the line ``deb-src http://deb.debian.org/debian buster-backports main contrib non-free`` to the file ``/etc/apt/sources.list`` first.
and is non-free required

2023-09-28 07:32 UTC, kamil-certat commented on docs/user/installation.rst
> +  * Enable the backport repository by the line ``deb-src http://deb.debian.org/debian buster-backports main contrib non-free`` to the file ``/etc/apt/sources.list`` first.
Thanks for mentioning this, I've failed yesterday on verifying in which part the package exactly ist. But today I've managed to find out, that only `main` is necessary

2023-09-28 12:21 UTC, kamil-certat commented
After testing in our environment - fixes to places, where bot modules are imported

2023-10-16 14:08 UTC, sebix approved these changes

2023-10-16 15:03 UTC, sebix commented
For further tests on more platforms I pushed your branch (with #2416) to the "unstable" package repo: https://build.opensuse.org/package/show/home:sebix:intelmq:unstable/intelmq

2023-10-16 15:09 UTC, sebix commented on debian/control
> +         python3-importlib-metadata,
In Debian 10 buster, this package is only available in backports. Operators need to enable this repository, for installing the IntelMQ deb package.

2023-10-16 15:34 UTC, sebix commented on debian/control
> +         python3-importlib-metadata,
we don't support Debian 10 anymore, so that is not relevant

2023-10-24 14:12 UTC, kamil-certat commented
Thanks for the unstable package - I'll try to test the integration with the DEB package in the next two weeks. If you had your own use cases for tests, it would be great if you also could do some tests. From my side - the change is now used and works great for in our systems.

2023-10-30 14:24 UTC, kamil-certat commented
@sebix I have just tested the integration with DEB package (IntelMQ from deb, additional bots from pip) - it works well! As it also works good in our instances for w few weeks already, I think we can merge it :)

2023-11-14 10:48 UTC, merged