STOMP+SSL-related changes: security fixes + convenience enhancement (+ doc updates/improvements)
certtools/intelmq pull request #2414
Opened 2023-10-07 22:59 UTC by zuo

The main purpose of this PR is to deal with the following two problems -- both related to how the `stomp.py` library deals with SSL:

* (1) **[ad security]** Numerous versions of `stomp.py`, IntelMQ needs to be compatible with, use the `ssl` module's tools in ways that suffers from certain security weaknesses. *In particular,* `stomp.py < 4.1.12` uses a deprecated helper: `ssl.wrap_socket()`; and, on the other hand, `stomp.py >=8.0, <8.1` mistakenly creates an `SSLContext` instance with the `check_hostname` flag unset; in both cases, an important negative result is that the hostname of the STOMP server is *not* checked during the TLS handshake (!).

* (2) **[ad admin convenience]** No version of `stomp.py` makes it possible to load the *system's default CA certificates* -- condemning administrators to bother with manual updates of the CA certificate(s) file, even if the certificate of the STOMP server the bots connect to could be verified using some of the publicly available CA certificates which are part of nearly all mainstream operating system distributions and web browsers... *Note:* this is the case with the upcoming new *n6* Stream API server's certificate.

An important part of the implementation of the aforementioned changes is a non-public helper class, `intelmq.lib.mixins.stomp._StompPyDedicatedSSLProxy` -- which implements a kind of transparent proxy object that wraps the `ssl` attribute of the `stomp.transport` module (originaly set to the `ssl` module object), replacing some of the `ssl` module's tools with their patched variants. *Note:* the `ssl` module itself and all its members are left untouched -- only the `ssl` member of the `stomp.transport` module is replaced with an instance of that class.

For more details -- see the docstrings and comments in the code. [*See the 3rd commit...*]

Together with the aforementioned changes, relevant parts of the documentation (including also the feeds spec and the changelog) have been appropriately updated, including also some extra details concerning the upcoming switch to the new variant of *n6* Stream API (the one with username+password-based authentication). [*Also, see the 3rd commit...*]

Plus, apart from all that, several additional (also STOMP-or-*n6*-integration-related) doc updates/improvements as well as very minor/cosmetic code tweaks have been made. [*See the 1st and 2nd commit...*]

2023-10-07 23:33 UTC, zuo commented on intelmq/lib/mixins/stomp.py
> +        return ssl_context.wrap_socket(sock, server_hostname=self.__server_hostname)
In a newer version of this commit (see below...), the code enforces TLSv1_2 as the `minimum_version`.

2023-10-10 19:00 UTC, zuo commented on docs/user/bots.rst
> +* `exchange`: STOMP *destination* to subscribe to, e.g. ``"/exchange/my.example.org/*.*.*.*"``
Without the ``` `` ``` marks rendering of the `*.*.*.*` fragment was wrong.

2023-10-10 21:03 UTC, sebix commented on docs/user/bots.rst
> +* `exchange`: STOMP *destination* to subscribe to, e.g. ``"/exchange/my.example.org/*.*.*.*"``
the backtick markup is correct, to display it as code/preformatted text

2023-10-11 14:24 UTC, kamil-certat requested changes
I have started the review, but I after a while of analysing it, I'd like to start with challenging some architectural decisions you've made.

I love the improvements in the security, however please see that the solution is really crafted for a very specific conditions, and can easily break with any upstream changes, as well as duplicate a lot of checks. As we support a library mode, I can imagine creating two objects of bots connecting to two different hosts in a one process - and then the Proxy will keep the first hostname and raise an exception.

Consider we re-design the solution in following way:

1. Do not check things that are already granted, like minimum version of Python, if it doesn't change the code flow.
2. Create a subclass of SSLContext, and override related methods there, instead of patching them. Keep the default behaviour any time the call isn't the one marking a special behaviour, but just use the `super()....` for that.
3. The proxy should override only the expected objects (SSLContext class, create_default_context etc.), and do not change the `ssl` behaviour in any other way.

If the conditions doesn't look like a call from expected stomp, do not raise - assume it was another legit use of the stomp etc., just not the one we want to secure.

2023-10-11 14:24 UTC, kamil-certat commented on intelmq/bots/outputs/stomp/output.py
> +    password: str = 'guest'   # (STOMP auth *passcode*)
More just a FYI, but basically, if parameters are set by StompMixIn, it shouldn't be necessary to repeat them in bot's class. As there is quite a long part with parameters' explanation, I'd put it in the Mixin class, and just leave a note in bots' classes where to look for them. On the other hand, here they are easier accessible. What do you think, @zuo & @sebix?

2023-10-11 14:24 UTC, kamil-certat commented on intelmq/lib/mixins/stomp.py
> +        assert len(host_and_ports) == 1
Do not rely on assertions in non-test code, they are intended for the debug purposes only, and can be easily [disabled with optimizations](https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement).

2023-10-11 14:24 UTC, kamil-certat commented on intelmq/lib/mixins/stomp.py
> +        self.__patch_ssl_related_stomp_stuff(host_and_ports)
```suggestion
        self.__patch_ssl_in_stomp(host_and_ports)
```

Or so, to make it look better ;)

2023-10-11 14:24 UTC, kamil-certat commented on intelmq/lib/mixins/stomp.py
> +        [(server_hostname, _)] = host_and_ports
Instead of _pack (L99), call, assert, unpack, ignore one, call_ please just write in L100:

```
_StompPyDedicatedSSLProxy.patch_stomp_transport_ssl(self.server)
```

and remove this function.

2023-10-11 14:24 UTC, kamil-certat commented on intelmq/lib/mixins/stomp.py
> +        assert getattr(stomp, 'transport', None) is not None
Please remove. Those conditions _are considered already guaranteed_, so verifying them again with the debug-only asserts should be considered unnecessary - it would make sense in a mathematical proof, but not in a service. It introduces an additional place, where we possibly should maintenance the check - e.g., for the consistency, if we drop the Python 3.7 support, this place should also be updated.

2023-10-11 20:52 UTC, zuo commented
> I have started the review, but I after a while of analysing it, I'd like to start with challenging some architectural decisions you've made.
> 
> I love the improvements in the security, however please see that the solution is really crafted for a very specific conditions, and can easily break with any upstream changes, as well as duplicate a lot of checks. As we support a library mode, I can imagine creating two objects of bots connecting to two different hosts in a one process - and then the Proxy will keep the first hostname and raise an exception.
[...]

OK, I will reconsider the design...

One question: could we drop support for `stomp.py < 4.1.12`? The hostname-related problem you mentioned above would disappear (as versions `>= 4.1.12` do not use `ssl.wrap_socket()` [at least not for `Python >= 3.7`], so the patched variant of it -- which is the only place where that early-stored `hostname` is used -- could be entirely removed).

2023-10-12 07:17 UTC, sebix commented
> One question: could we drop support for `stomp.py < 4.1.12`? The hostname-related problem you mentioned above would disappear (as versions `>= 4.1.12` do not use `ssl.wrap_socket()` [at least not for `Python >= 3.7`], so the patched variant of it -- which is the only place where that early-stored `hostname` is used -- could be entirely removed).


Yes, absolutely.
By way of comparison: Debian 10 buster and Ubuntu 20.04 focal have python3-stomp == 4.1.19.

We can also consider dropping support for < 6.
We seek for compatibility and don't want to enforce that users strictly need the absolute latest version of a library (makes sense in very controlled and similar environments), but if the required effort is high, the reward is low (it affects only one single bot, not the core), dropping compatibility is reasonable.

2023-10-19 18:26 UTC, sebix approved these changes
The more important review comes from @kamil-certat as he is a user/operator of the bot and knows more details, also from a user- and admin perspective.

2023-10-19 18:26 UTC, sebix commented on intelmq/bots/outputs/stomp/output.py
> +    password: str = 'guest'   # (STOMP auth *passcode*)
Yes, re-defining them is not necessary

2023-10-19 19:38 UTC, zuo commented
@sebix @kamil-certat 

OK, this is a redesigned version + with a few additional minor improvements/fixes/updates -- in particular, minimum `stomp.py` version has been changed from `4.1.8` to `4.1.12`, and a package name has been fixed in `debian/control` (see the relevant commit...).

2023-10-24 13:47 UTC, kamil-certat approved these changes
I think it looks good. Thanks for the change!

2023-11-06 13:32 UTC, kamil-certat commented
@sebix @aaronkaplan Could you please merge this change? It's quite important for changes in n6 (using default CAs).

2023-11-06 13:33 UTC, kamil-certat approved these changes

2023-11-07 12:39 UTC, kamil-certat commented
@zuo We have merged the new docs system, may you merge `develop` and copy your changes in documentation to `docs/user/bots.md`?

2023-11-07 21:41 UTC, zuo commented
> @zuo We have merged the new docs system, may you merge `develop` and copy your changes in documentation to `docs/user/bots.md`?

OK, I will.

2023-11-21 14:48 UTC, sebix commented
I rebased the PR on the branch 'develop' and moved all docs to the new files. As the documentation changes were spread over five commits, I squashed them all together, because keeping the changes apart in separate commits, and moving every single change manually to the new format would be a heck of a lot of effort.

As @kamil-certat approved the PR, I will merge it after the CI checks pass.

2023-11-21 15:03 UTC, merged

2023-11-23 21:10 UTC, zuo commented
@sebix @kamil-certat Oh, thank you for the rebase and merge! And I am sorry I haven't managed to do that promptly!

2023-11-24 13:12 UTC, sebix commented
@zuo Thank your for improving, maintaining and contributing to IntelMQ!