bots/collectors/api: make socket file permissions configurable
certtools/intelmq pull request #2417
Opened 2023-10-20 07:36 UTC by monoidic

By default, `tornado.netutil.bind_unix_socket` creates socket files with `600` permissions and which have the owner and group of the creating user (intelmq). This does not work well in the common case of the process at the other end of the socket not being a process running as the intelmq user.
This commit adds `socket_perms` and `socket_group` configuration options to the bot.

2023-10-24 13:53 UTC, kamil-certat requested changes
Thank you for the change! The code looks good. Could you please update the changelog (`CHANGELOG.md`) and possibly also the Bot's documentation in `docs/bots.rst`?

2023-10-25 16:52 UTC, sebix commented
Good change, as @kamil-certat said. With docs, it would be good to merge.

2023-10-31 14:01 UTC, monoidic commented
Done. Apologies for the delay

2023-10-31 14:49 UTC, kamil-certat approved these changes

2023-11-14 10:51 UTC, kamil-certat commented
@monoidic In the meantime, we have changed the documentation system. May you merge develop and move your docs changes to the docs/user/bots.**md**?

2023-11-21 14:12 UTC, sebix commented
I fixed the merge errors (some unrelated changes were part of the PR's commits), now ready for merge after the CI checks pass.

2023-11-21 14:45 UTC, sebix commented
Merging, as reviewed OK by @kamil-certat

2023-11-21 14:45 UTC, merged