Changes documentation to mkdocs
certtools/intelmq pull request #2419
Opened 2023-10-31 16:08 UTC by gethvi

WIP. More polish incoming.

2023-11-02 13:51 UTC, sebix requested changes

2023-11-02 13:51 UTC, sebix commented on setup.py
> +with open(os.path.join(os.path.dirname(__file__), 'README.md')) as handle:
Please set `long_description_content_type='text/markdown'` (see https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/)

2023-11-02 14:03 UTC, gethvi commented on setup.py
> +with open(os.path.join(os.path.dirname(__file__), 'README.md')) as handle:
Thanks. Done.

2023-11-06 13:57 UTC, kamil-certat reviewed
I haven't checked all changes in the docs (this will come with the usage, but I feel you also addressed some my concerns about the docs structure :D). I love the change, and want to see it online <3

However, could you please bring back to the README two things:
- IntelMQ logo (because it looks sad on GitHub without it)
- European funding info (because I'm pretty sure there are still active legal requirements to say it clearly).

I'd also add a link to docs in the README - even if it would be redundant on the docs website, it's important in GitHub

2023-11-06 13:57 UTC, kamil-certat commented on .github/workflows/build-docs.yml
> +          pip install mkdocs-material mike lunr pygments mkdocstrings[python] mkdocs-material mkdocs-glightbox mkdocs-redirects mkdocs-minify-plugin
Wouldn't it be possible to reuse the list from `setup.py`? Maybe by creating a new extra? Otherwise, we need to again maintain two separated dependency lists.

2023-11-06 13:57 UTC, kamil-certat commented on Makefile
> +# SPDX-License-Identifier: AGPL-3.0-or-later
+1 for Makefile
+1 for using `pip-compile`

-1 for pushing Makefile with tools that aren't installed. `pip-compile` isn't so far mentioned anywhere in the IntelMQ, so I'd suggest leaving this Makefile with `docs` only (for now)

2023-11-06 13:57 UTC, kamil-certat commented on mkdocs.yml
> +site_url: https://intelmq.org
Should it be `intelmq.org` or `docs.intelmq.org`?

2023-11-06 14:14 UTC, gethvi commented on Makefile
> +# SPDX-License-Identifier: AGPL-3.0-or-later
Removed.

2023-11-06 14:14 UTC, gethvi commented on mkdocs.yml
> +site_url: https://intelmq.org
Fixed.

2023-11-06 14:42 UTC, aaronkaplan commented on .github/workflows/build-docs.yml
> +          pip install mkdocs-material mike lunr pygments mkdocstrings[python] mkdocs-material mkdocs-glightbox mkdocs-redirects mkdocs-minify-plugin
@kamil-certat we'll do that in a second step, ok? 
I have @gethvi 's attention briefly now. And this does not seem like it;'s critical. Will merge now into develop and then fix broken things

2023-11-06 14:43 UTC, aaronkaplan commented on .github/workflows/build-docs.yml
> +          pip install mkdocs-material mike lunr pygments mkdocstrings[python] mkdocs-material mkdocs-glightbox mkdocs-redirects mkdocs-minify-plugin
I.e. I'll take the blame to clean it up in case it's broken

2023-11-06 14:43 UTC, merged