Add extract_cve_from_tag to Shadowserver parser _config.py
certtools/intelmq pull request #2457
Opened 2024-02-05 08:55 UTC by th-certbund

"extract_cve_from_tag" returns a sorted comma separated list of CVEs included with "tag" in the Vulnerable-HTTP report, e.g.

extract_cve_from_tag("affected-software;cve-2023-12345;cve-2024-56789;ssl;ssl-freak;vpn")
-> "cve-2023-12345,cve-2024-56789"

to be stored in "extra.cve" by adding

         [
            "extra.cve",
            "tag",
            "extract_cve_from_tag"
         ],

to the intelmq.json schema.

2024-02-05 16:21 UTC, elsif2 commented
The `functions` map needs to be updated to include "extract_cve_from_tag".

2024-02-05 16:30 UTC, elsif2 approved these changes

2024-02-06 08:48 UTC, sebix requested changes

2024-02-06 08:48 UTC, sebix commented on intelmq/bots/parsers/shadowserver/_config.py
> +        return None;
```suggestion
        return None
```

2024-02-07 13:08 UTC, merged