Fixes #2484
certtools/intelmq pull request #2485
Opened 2024-03-21 11:02 UTC by barbich

Fix: Import correct YAML library (ruaml) to resolve compatibility issue in intelmq_gen_feeds_conf

2024-03-21 11:16 UTC, kamil-certat requested changes

2024-03-21 11:16 UTC, kamil-certat commented on contrib/feeds-config-generator/intelmq_gen_feeds_conf
>      print("[-] Please install yaml using the following command: 'pip install pyyaml'.", file=sys.stderr)
This error message isn't correct anymore

2024-03-25 13:57 UTC, sebix requested changes, later dismissed

2024-03-25 13:57 UTC, sebix commented on contrib/feeds-config-generator/intelmq_gen_feeds_conf
>      print("[-] Please install yaml using the following command: 'pip install pyyaml'.", file=sys.stderr)
```suggestion
    print("[-] Please install ruamel.yaml using the following command: 'pip install ruamel.yaml'.", file=sys.stderr)
```

2024-03-25 13:59 UTC, sebix commented on contrib/feeds-config-generator/intelmq_gen_feeds_conf
>      print("[-] Please install yaml using the following command: 'pip install pyyaml'.", file=sys.stderr)
fixed

2024-05-05 11:32 UTC, merged