ENH: Caching, advanced mapping and separating events for MISP Feed output bot
certtools/intelmq pull request #2509
Opened 2024-07-04 14:45 UTC by kamil-certat

MISP Feed output bot got new features:

 * caching incoming messages to not re-generate on every run;
 * an ability to select which fields should be mapped and set additional parameters for attributes;
 * an ability to group messages in different MISP events, based on a field.

The bot is fully backward-compatible. By default, the previous behaviour is kept.

In addition, code related to Python 3.6 was removed and the message library was fixed not to modify the original dict instance.

This PR replaces on PR #2505.

2024-07-08 11:40 UTC, kamil-certat commented
Yeah, finally green :tada:

2024-07-08 11:51 UTC, sebix commented
Are you using it in production?

2024-07-08 12:55 UTC, kamil-certat commented
We started using it on staging, found some pain points, and now I'll test it & hopefully promote to prod in a few days - so, not yet, but soon ;)

2024-07-09 07:35 UTC, sebix commented
There's not much I can check here without reading the MISP code and docs and setting up an instance.

Maybe @Rafiot, can you have a glimpse?

2024-07-09 08:42 UTC, aaronkaplan requested changes, later dismissed
minor changes requested pls.

2024-07-09 08:42 UTC, aaronkaplan commented on docs/user/bots.md
>  hour", string.
what happens when set to 0 ?

2024-07-09 08:42 UTC, aaronkaplan commented on docs/user/bots.md
> +as not usable for IDS.
clear and understandable. Cool

2024-07-09 08:42 UTC, aaronkaplan commented on docs/user/bots.md
> +for all grouping events together.
this is not 100% clear for me yet:

will it collect events until (... until when?...) and then sort and group by this viel?
I think rephrasing this slightly makes it clearer in the documentaiton.

2024-07-09 08:42 UTC, aaronkaplan commented on intelmq/bots/outputs/misp/output_feed.py
> +    )
why the tuple?

2024-07-09 08:42 UTC, aaronkaplan commented on intelmq/bots/outputs/misp/output_feed.py
> +            event = self._generate_new_event(key)
don't we want to support at add a default tag to an event, such as "FEED:Source=intelmq" ?
Of course, this should be configured by the user.

2024-07-09 08:42 UTC, aaronkaplan commented on intelmq/bots/outputs/misp/output_feed.py
> +    def _load_event(self, file_path: Path, key: str):
missing function docstring ?

2024-07-09 08:42 UTC, aaronkaplan commented on intelmq/bots/outputs/misp/output_feed.py
> +    def _generate_new_event(self, key):
missing function docstring?

2024-07-09 08:42 UTC, aaronkaplan commented on intelmq/bots/outputs/misp/output_feed.py
> +    def _add_message_to_feed(self, message: dict):
missing func docstring?

2024-07-09 08:42 UTC, aaronkaplan commented on intelmq/bots/outputs/misp/output_feed.py
> +    def _default_mapping(self, obj: "MISPObject", message: dict):
docstring?

2024-07-09 08:42 UTC, aaronkaplan commented on intelmq/bots/outputs/misp/output_feed.py
> +    def _extract_misp_attribute_kwargs(self, message: dict, definition: dict) -> dict:
docstring? not just # comment

2024-07-09 08:42 UTC, aaronkaplan commented on intelmq/bots/outputs/misp/output_feed.py
> +    def _custom_mapping(self, obj: "MISPObject", message: dict):
same

2024-07-09 08:42 UTC, aaronkaplan commented on intelmq/bots/outputs/misp/output_feed.py
> +    def _generate_feed(self, message: dict = None):
same

2024-07-09 08:42 UTC, aaronkaplan commented on intelmq/lib/mixins/cache.py
> +    """Provides caching possibilities for bots
quick line (link to documentation on the mixins) ?

2024-07-09 08:47 UTC, aaronkaplan commented
My main request is:

1) give the possibility (or document it) how to add default tags to events (such as "FEED:Source=intelmq") to any event which gets generated via this feed. Adding a default tag helps in sorting out automatically added events and attributes in case something goes wrong.
2) make sure the users understand in the documentation how feeds work. Linking to the MISP documentation and what each parameter when including the MISP feed actually means.
For example, did you know that if  you set "caching:enabled" in a MISP feed, then that means the feed events and attributes don't get added to the `events` (and `attributes`) table in MISP. 
It's totally non-intuitive. 
Why am I saying this? I had to figure it out the hard way myself.
3) basically we need a *tutorial* on docs.intelmq.org  on how to run this properly!
It's a very cool feature and addition but you can quickly shoot yourself in the foot if you don't know how it works and what every parameter in MISP means.

2024-07-09 08:55 UTC, kamil-certat commented on intelmq/bots/outputs/misp/output_feed.py
> +    )
It's not a tuple ;) It's a Python way to put the string into next line (or split into multiple strings) to avoid line-length limit - although it's my fault. The rules we enforce in the repository are very weak, so weak that my almost every time wants tot reformat a lot, and sometimes I forget reverting changes not related to my code.

BTW, I think more and more that we would profit from enforcing black/ruff instead of weak pycodestyle.

2024-07-09 08:57 UTC, kamil-certat commented on intelmq/bots/outputs/misp/output_feed.py
> +            event = self._generate_new_event(key)
It's an interesting request, could you please elaborate how do you see it? I was focused on what we need now (so I didn't include a few different things I was thinking about), but if you have a specific idea you think it would be important to include now - let's share.

2024-07-09 09:00 UTC, kamil-certat commented on intelmq/bots/outputs/misp/output_feed.py
> +    def _load_event(self, file_path: Path, key: str):
Not at all. If you wish to document `_load_event` with `This function loads an event from file`, feel free, but I disagree with enforcing a docstring requirement for every function. It should happen when the function is complex, otherwise it's useless. Over-commenting is not a good practice. If there is anything you don't understand in the function, please let me know.

2024-07-09 09:01 UTC, kamil-certat commented on intelmq/bots/outputs/misp/output_feed.py
> +    def _generate_new_event(self, key):
Disagree it's needed here.

2024-07-09 09:01 UTC, kamil-certat commented on intelmq/bots/outputs/misp/output_feed.py
> +    def _add_message_to_feed(self, message: dict):
Disagree it's needed here.

2024-07-09 09:01 UTC, kamil-certat commented on intelmq/bots/outputs/misp/output_feed.py
> +    def _default_mapping(self, obj: "MISPObject", message: dict):
Disagree it's needed here.

2024-07-09 09:01 UTC, kamil-certat commented on intelmq/bots/outputs/misp/output_feed.py
> +    def _generate_feed(self, message: dict = None):
Disagree it's needed here.

2024-07-09 09:01 UTC, kamil-certat commented on intelmq/bots/outputs/misp/output_feed.py
> +    def _custom_mapping(self, obj: "MISPObject", message: dict):
Disagree it's needed here.

2024-07-09 09:10 UTC, kamil-certat commented
Thanks for the review!

re 1: It's a good idea, I'll look into it. I was concentrated on what we actually need, and I do think there are more things we can improve in the bot.
re 2: It's a good point, I will point to the MISP documentation. I also had to explore what we really can do, the PyMISP documentation wasn't really helpful :D 
re 3: yeah, I agree it needs a tutorial (and I've planned it), but it's a separated thing, I won't include it here. My plan is to write a blog post once we establish the final integration internally, and then we could include it in the documentation as well. I expect to publish it around September, hopefully. There is a queue of what I'd like to write about, and a limited time ;)

2024-07-09 14:36 UTC, kamil-certat commented on docs/user/bots.md
> +for all grouping events together.
What do you think about the current version?

> will it collect events until (... until when?...) and then sort and group by this viel?

This field is responsible only for separating using the field. Collecting & holding is a different setting, that can be used together, but you don't have to. Let's have a look at the new description

2024-07-16 11:24 UTC, kamil-certat commented on docs/user/bots.md
>  hour", string.
I've looked in the code, and it looks like in such case, this would be a ValueError. However, you can use "0 hours" what should result in creating a new MISP event for every IntelMQ event.

2024-07-16 12:54 UTC, kamil-certat commented
@aaronkaplan 

Could you have a look again? I have implemented tagging as well as rewritten the documentation, added config examples, implemented validation in the `check` method and refactored code, including renaming methods to be more clear what they do or adding doc strings where I found it useful. I have also added descriptions to complex test cases explaining what should happen.

I do admit that the configuration of the bot is complex. I did my best to marriage flexibility and readability, but I think in the future we may eventually redesign this configuration, based on feedback. I'm also open for any suggestions.

2024-07-29 09:38 UTC, aaronkaplan commented on intelmq/bots/outputs/misp/output_feed.py
> +    )
I am also using black more and more...

2024-08-27 09:42 UTC, sebix commented
@aaronkaplan you requested some changes to this PR and @kamil-certat implemented various changes based on your feedback. Can you please re-check?

2025-08-29 11:41 UTC, sebix commented
@aaronkaplan this PR is waiting for your approval

2025-10-23 21:08 UTC, aaronkaplan commented
Still need to test against a misp server

2025-10-24 09:41 UTC, sebix commented
rebased on develop. there were quite some conflicts to fix.

2025-10-24 09:48 UTC, sebix commented
now the JSON parser test fails, the output differs to the expected one.

The PR contains changes in `intelmq/lib/message.py`. I don't know yet if this is a rebase error or an error in the code.

2025-10-24 09:54 UTC, sebix commented
> Still need to test against a misp server

As discussed yesterday, I'll take this over

2025-10-26 20:01 UTC, sebix requested changes
Found problems in the docs and in the changes of the cache mixin

2025-10-26 20:01 UTC, sebix commented on intelmq/lib/mixins/cache.py
> +        return size
```suggestion
    def cache_lpush(self, key: str, value: Any) -> int:
        # Returns the length of the list after pushing
        size = self.__redis.lpush(key, value)
        return size
```

I appreciate the new function, but why is the name of the list not a parameter, but fixed?
Also, why is the value a dict?

The new functions are also missing in the docs in `docs/dev/bot-development.md`

2025-10-26 20:01 UTC, sebix commented on intelmq/lib/mixins/cache.py
> +        return self.__redis.llen(self.bot_id)
```suggestion
    def cache_llen(self, key: str) -> int:
        return self.__redis.llen(key)
```

The new function is missing in the docs in `docs/dev/bot-development.md`.

2025-10-26 20:01 UTC, sebix commented on intelmq/lib/mixins/cache.py
> +        return json.loads(data)
```suggestion
    def cache_rpop(self, key: str) -> dict:
        data = self.__redis.rpop(key)
        return data
```

The new function is missing in the docs in `docs/dev/bot-development.md`.

2025-10-26 20:01 UTC, sebix commented on docs/user/bots.md
> +use the same MISP Event as long as it's allowed by the `interval_event`.
I think this parameter name is misleading and unintuitive. The name "separator" is most often used to specify the element that separates joined data.

From the description, I gather it is actually a grouping or aggregation key.

2025-10-26 20:01 UTC, sebix commented on docs/user/bots.md
> +```
An empty value causes an exception:
```
  File "intelmq/bots/outputs/misp/output_feed.py", line 262, in _extract_misp_attribute_kwargs
    for parameter, value in definition.items():
                            ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'
```

```suggestion
```yaml
attribute_mapping:
  source.ip: {}
  feed.name:
    comment: event_description.text
  destination.ip:
    to_ids: False
```

2025-10-27 09:21 UTC, kamil-certat commented
I'm working on a few improvements / additional requirements right now, a new code should come today or tomorrow. I'll then address comments

2025-10-27 15:27 UTC, sebix commented
Documentation for the new parameter `flat_events` is missing

2025-10-27 15:29 UTC, kamil-certat commented on intelmq/lib/mixins/cache.py
> +        return size
The idea was to create a message caching for the bot which would make it easy to use, completely abstract from the underlying implementation, not a simple wrapper over the Redis (see e.g. `cache_set`). This is why they do not follow exact the same naming as Redis library, and do additional things.

I have now mixed feelings in which direction it should go. I see two general options:
* renaming my new methods to something more clear, like `cache_dict`, `get_cached_dict`
* go with the simple wrapping over Redis library

I both cases, I would consider also making a key optional (and using bot ID as the default). If going with the first option, then I'd also handle transforming messages to the JSON and back. 

@sebix what do you think is better?

2025-10-27 15:30 UTC, kamil-certat commented on docs/user/bots.md
> +use the same MISP Event as long as it's allowed by the `interval_event`.
`grouping_key` sounds much better, I'll change it

2025-10-27 15:31 UTC, kamil-certat commented
I'm aware of that, I'll adjust documentation tomorrow

2025-10-27 15:33 UTC, kamil-certat commented
I also have to add matching unit tests ;)

2025-10-27 19:04 UTC, sebix commented on intelmq/lib/mixins/cache.py
> +        return size
> * renaming my new methods to something more clear, like `cache_dict`, `get_cached_dict`

These names do not indicate in any way that a FIFO queue is used, but instead make the impression that a dictionary is the cache.
What about `queue_push` and `queue_pop`?

>     * go with the simple wrapping over Redis library

It would be more generic and slightly lower-level. (However, redis/valkey are not that low-level anyway :) )

> I both cases, I would consider also making a key optional (and using bot ID as the default). If going with the first option, then I'd also handle transforming messages to the JSON and back.

I understand your desire for simplicity, but I have doubts about ambiguity. With an optional key, some possible interfaces are:
- `func(key: Optional[str], value: Any)`: Requires calling it with `None` as the first parameter: `func(None, foobar)`. No big difference to using `self.bot_id`: `func(self.bot_id, foobar)`
- `func(value: Any, key: Optional[str] = None)`: The order of parameters is the complete opposite of anything else in IntelMQ and elsewhere.
- `func(key_or_value: Any, value_if_key: Optional[Any])` allowing to call `func(value)` and `func(key, value)`: Too complicated. Not very KISSy :kiss:

2025-10-28 09:14 UTC, kamil-certat commented on intelmq/lib/mixins/cache.py
> +        return size
> I understand your desire for simplicity, but I have doubts about ambiguity. With an optional key, some possible interfaces are:

I'd never ever thought about option 3, and the option 1 is not simplifying anything :sweat_smile: So the 2 is the only one I would ever consider

But as my original idea seems to introduce too many questions, I'll move forward with your original idea of wrapping Redis library and let the developer use it flexible.

2025-10-28 09:54 UTC, kamil-certat commented
BTW, all methods were documented in bot-development :thinking:

2025-10-28 09:58 UTC, sebix commented
> BTW, all methods were documented in bot-development 🤔

Oh, sorry. I don't know where I was looking.

2025-10-28 10:53 UTC, sebix commented on docs/user/bots.md
> +To ensure saving on reload without any delay, you should also set `_sighup_delay` parameter.
That's not a parameter, but an internal variable

2025-10-28 11:59 UTC, sebix commented on docs/user/bots.md
> +To ensure saving on reload without any delay, you should also set `_sighup_delay` internal variable.
What do you want to say with this last sentence?
`_sighup_delay` is not a parameter. It's a switch that developers can use to indicate bot-specific behavior. It is true by default.

Why does the user need to do anything here?

2025-10-28 12:01 UTC, sebix commented on docs/user/bots.md
> +  _sighup_delay: false
Here, you do the opposite of what is written above, disabling it instead of activating it.

And still, this is not something a user should need to do. If the bot needs to disable this flag (maybe depending on other parameters), do it in `init()`.

2025-10-28 12:13 UTC, sebix requested changes

2025-10-28 12:13 UTC, sebix commented on docs/dev/bot-development.md
> + data). You won't see caches from one in the another. For example, if adding a key-value pair using
```suggestion
Caching key-value pairs and queue caching are two different mechanisms. The functions in the first list are designed
 for arbitrary values, while the latter ones are primarily for temporarily storing messages, but can also handle other data
 types. You won't see caches from one in the other. For example, if adding a key-value pair using
```

2025-10-28 12:13 UTC, sebix commented on docs/dev/bot-development.md
> +self.cache_lpush(self.bot_id, json.dumps(message))
Why not use `message.to_json` directly?
```suggestion
self.cache_lpush(self.bot_id, self.receive_message().to_json(jsondict_as_string=True))
```

2025-10-28 12:13 UTC, sebix commented on docs/dev/bot-development.md
> +self.cache_lpush(self.bot_id, json.dumps(message))
Or: `Message.serialize`

2025-10-28 12:13 UTC, sebix commented on docs/dev/bot-development.md
> +)
Untested:

```suggestion
message_obj = MessageFactory.unserialize(
    data, harmonization=self.harmonization, default_type="Event"
)
```
I think the two optional parameters are unnecessary too.

2025-10-28 12:19 UTC, kamil-certat commented on docs/user/bots.md
> +  _sighup_delay: false
This is a good idea, I'll do it so in `init()`. I used wrong wording in the docs. The thing is: if you keep the `_sighup_delay` enabled, then after receiving the reloading signal, the bot waits for the next incoming message to actually do the reloading. This means, the accumulated (cached) events won't be saved. This can be very unfortunate delay

2025-10-28 12:20 UTC, kamil-certat commented on docs/dev/bot-development.md
> +)
I'm almost sure the default_type was necessary, but I'll check it again.

2025-10-28 12:45 UTC, kamil-certat commented on docs/user/bots.md
> +  _sighup_delay: false
Actually, I'm stupid, I have already solved it by setting the right defaults... But I'll do it conditionally if using bulk saving

2025-10-28 12:50 UTC, kamil-certat commented on docs/dev/bot-development.md
> +self.cache_lpush(self.bot_id, json.dumps(message))
Using the first. I have copied the code from the bot, where the JSON representation is used later.

2025-10-28 12:58 UTC, kamil-certat commented on docs/dev/bot-development.md
> +)
The first is recommended, the second is necessary to match the dumping code.

1) if the harmonization is not provided, the code will _read it from the file_, and not use any already loaded version. Reading files and processing JSON is in Python quite expensive operation, it's much better to provide the ready harmonization.
2) the second depends on setting `with_type` when serializing the message. As I didn't set it on serialization, I have to provide type on deserialization. I could do it the other way around, there is no difference - but one or another has to be set.

2025-10-28 13:35 UTC, sebix commented on docs/dev/bot-development.md
> +)
Ad 1: True, we should probably cache that file -> different topic
Ad 2: `MessageFactory` is the preferred way of convering Messages to JSON back and forth. I agree, that both ways need to be compatible with each other. Let's refactor this doc section later when improving the overall docs.

2025-10-28 13:37 UTC, sebix approved these changes

2025-10-28 13:37 UTC, merged