ENH: Add ability to copy more fields from the report
certtools/intelmq pull request #2513
Opened 2024-07-09 12:33 UTC by kamil-certat

Sometimes collectors sets more context information, e.g. the source file name. Currently, parsers usually remove those non-standard information. With this change, we let the user decide to copy more information to the event.

In addition, the currently copied fields were documented.

Real use case: the HTTP collector sets filename when extracting data from an archive. This filename contains an information we want to include in the final event, which we cannot retrieve in any other way.

2024-07-09 14:52 UTC, sebix requested changes
I'm not convinced by the parameter name. Custom fields sound very generic and is ambiguous, also it lacks any mention of _report_ or _event_.

What about `replicate_report_fields(_to_event)`? It's longer, but it speaks by itself.

2024-07-09 14:52 UTC, sebix commented on intelmq/lib/bot.py
> +
When this code is in `intelmq.lib.bot.ParserBot.process`, it will not be active in all parsers as the above documentation suggests.

Adding it to `intelmq.lib.message.Report.__init__` (and passing the parameter in `intelmq.lib.bot.Bot.new_event` will cover all cases AFAIK.

2024-07-09 14:53 UTC, sebix commented on CHANGELOG.md
> +  (PR# by Kamil Mankowski).
```suggestion
- `intelmq.lib.bot.ParserBot`: add `copy_custom_fields` parameter allowing copying additional fields from the report, e.g. `extra.file_name` (PR#2413 by Kamil Mankowski).
```

2024-07-10 07:22 UTC, kamil-certat commented on intelmq/lib/bot.py
> +
Hmm, you mean some parsers do not use the `process`? Then they do not use the `default_fields`, right?

2024-07-10 07:32 UTC, kamil-certat commented
@sebix I'm open to name changes, but hmm, I'm not convinced with your suggestion either. Actually, my original idea was `copy_fields` (as direct similarity to `default_fields`) or `copy_report_fields`. However, I realised it would then create a confusion that those are _all_ copied (not parsed) fields, which is not true - creating an event from the report has a hardcoded list of fields to replicate. This is how `additional` came to play :D

What would you say about:
- `extended_report_fields`
- `copy_additional_report_fields`
- `replicate_extra_report_fields` (although this is too narrow, with a different harmonisation it could be more than `extra.*`)
- `extendend_report_fields_to_copy` (actually, this suggests we want a list, while `copy_...` sounds like Y/N question)

...or any other? I think that the last sounds currently the best

2024-07-10 08:31 UTC, sebix commented on intelmq/lib/bot.py
> +
It can be overwritten

2024-07-11 10:29 UTC, kamil-certat commented on intelmq/lib/bot.py
> +
Of course, it could be, but I didn't know it's a broad practice - I've looked at the source code, and you're right, a lot of parsers rely on overriding the whole `process`. I'll move the code to the `new_event`, and I think we should consider moving support of `default_fields` there as well as this is something I'd expect all parsers to support (but it's a separated thing).

2024-07-22 05:54 UTC, sebix commented
Some remarks from @th-certbund:

2024-07-22 05:55 UTC, sebix commented
Some remarks by @th-certbund:
- "custom" is also very generic
- "report" is ambiguous too
- What about "copy_collector_provided_fields" or similar?

2024-07-25 13:17 UTC, aaronkaplan approved these changes
looks good, I read it and it's understandable.

2024-07-25 13:19 UTC, aaronkaplan commented
thank you @kamil-certat !!

2024-07-25 13:19 UTC, merged