ENH: Sieve variable support
certtools/intelmq pull request #2514
Opened 2024-07-15 10:38 UTC by monoidic

This fixes issue #2486

2024-07-15 16:47 UTC, sebix commented
Wow, very neat again!

@kamil-certat as you have a use-case of this feature, do you want to have a look at the diff?

2024-07-25 10:13 UTC, kamil-certat requested changes
I love the change, as well as the refactoring and formatting against black/ruff. I have some NIT comments and one or two clarification questions, but also a one big one: what has happened to the test `test_extra_dict`? Have you found it duplicated (if so, please remove test files and say what duplicates it)?

Please also update the bot documentation to describe variables as well as the changelog.

And as a discussion, I have two things I'm unsure, but I don't find it blocking:
1) a variable can be in place of typed values, like `Bool`. Shouldn't we then ensure in code that the variable has the correct value?
2) variables look like extremely promising for the future, but I also ask myself - wouldn't it be also nice just allow syntax like `ifd.field1 = idf.field2`? The current use case looks like only supporting this.
3) I'd think about extending the validation - I haven't seen if there is any place where we would try to statically validate that the requested variable was previously defined

2024-07-25 10:13 UTC, kamil-certat commented on intelmq/bots/experts/sieve/expert.py
> +                Event,
NIT: it could be any _Message_. Although it's rare, it is possible to process Report object as well

2024-07-25 10:13 UTC, kamil-certat commented on intelmq/bots/experts/sieve/expert.py
> +        self.sieve = self.read_sieve_file(file_path, self.metamodel)
NIT: I'd ask to rename `sieve` here or in the bot class - just for sake of confusing, those are two variables with the same name, relatively close to each other, and with a different meaning. Maybe name it in the bot as `sieve_model`?

2024-07-25 10:13 UTC, kamil-certat commented on intelmq/bots/experts/sieve/expert.py
> +        return ret
Did you decide to rewrite because of readability, or there is a change I don't see? For sake of readability, I'd think about `return not ret if cond.neg else ret`. In cases like this I find it a little clearer to keep this in a one line. But it's personal preference.

2024-07-25 10:13 UTC, kamil-certat commented on intelmq/bots/experts/sieve/expert.py
> +        return self._string_op_map[op](event[key], value)
I'd ask for a short explanation why:
* `process_single_string_match`
* `process_multi_string_match`
* `process_multi_numeric_match`
were changed. 

The `value(s).value(s)` -> `value(s)` change looks clear, it's been moved upper to the operator maps, but I'm unsure about dropped conversion and special cases for numeric match, where is it handled now? (I might have missed it)

2024-07-25 10:13 UTC, kamil-certat commented on intelmq/bots/experts/sieve/expert.py
> +            type = SieveExpertBot._harmonization[num_match.key]["type"]
I'd think about explicit setting the harmonisation in the `SieveModel` class. Now it's a little strange that the `SieveModel` class, just used by `SieveExpertBot`, then silently have a backref to `SieveExpertBot` - and thus to a value that by default is `None`. If you try to draw how classes depend on each other, I would be surprised seeing a circle between classes not inheriting on each other.

2024-07-25 10:13 UTC, kamil-certat commented on intelmq/tests/bots/experts/sieve/test_expert.py
> +    def test_variables(self):
(!) What has happened to the`test_extra_dict` test case?

2024-07-29 12:32 UTC, monoidic commented on intelmq/bots/experts/sieve/expert.py
> +        return self._string_op_map[op](event[key], value)
The removed code in `process_multi_numeric_match` was after an unconditional `return` and hence completely dead code.
The rest of the changes are in order to uniformly add `resolve_value` to all match functions via `_cond_map`, to allow for the use of variables in those matches.

2024-07-29 12:34 UTC, monoidic commented on intelmq/bots/experts/sieve/expert.py
> +            type = SieveExpertBot._harmonization[num_match.key]["type"]
Perhaps splitting the bot in two was not a great idea. I re-merged them, though kept the previous `SieveModel.process` separate from `SieveExpertBot.process` as `model_process`

2024-07-29 12:36 UTC, monoidic commented on intelmq/tests/bots/experts/sieve/test_expert.py
> +    def test_variables(self):
Accidentally discarded the commi which added this.

2024-07-29 13:26 UTC, monoidic commented
> what has happened to the test test_extra_dict?

Accidentally discarded newer commits to the Sieve bot. I noticed it in the commit diff ~a week ago, but got distracted and forgot to address it...

> a variable can be in place of typed values, like Bool. Shouldn't we then ensure in code that the variable has the correct value?

This has actually been addressed in the code. The `resolve_value` method which resolves variables (if needed) has a parameter, `expected_types`, expecting a type or tuple thereof. If specified, it raises an exception if the variable's type is not as expected.
Or do you mean that an expected type could somehow be specified in the Sieve file itself as well?

> variables look like extremely promising for the future, but I also ask myself - wouldn't it be also nice just allow syntax like `ifd.field1 = idf.field2`? The current use case looks like only supporting this.

At the moment, yes.
The parsing end would technically accept both `append extra.list $elem` as well as `append $list $elem` at the moment (with the former appending a value given in a variable to a list in the event, and the latter working purely with variables), though the processing end does not handle variables as keys yet.
Allowing event keys to be used like that could be an option, but seems like a slight downgrade feature-wise (e.g any temporary variables which are not meant to end up in the event itself would have to exist under random keys of the event and be cleared out afterwards) while requiring all the same new validation that's been added for variables anyway.
Though for some cases, it would be more ergonomical.

> I'd think about extending the validation - I haven't seen if there is any place where we would try to statically validate that the requested variable was previously defined

I'd expect `check()` to be the place for this.

2024-07-31 10:28 UTC, kamil-certat approved these changes
Thanks for the explanation! It sounds sufficient for me.

Before it gets merged, I'd ask you to verify / add a test that `check()` would reject a sieve file with variable used without being declared beforehand

2024-08-27 09:45 UTC, sebix commented
Merging this, based on @kamil-certat's positive review.

For the last request on a check for undeclared variables, I opened https://github.com/certtools/intelmq/issues/2526

2024-08-27 09:55 UTC, merged